using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SBISCCMWeb.Models.PreviewMatchData.DCP
{
    public class DCP_Base
    {

        public string DnBDUNSNumber { get; set; }
        public string APIType { get; set; }
        public string TransactionTimestamp { get; set; }
        public string ServiceTransactionID { get; set; }
        public string ApplicationTransactionID { get; set; }
        public string ResultID { get; set; }
        public string ResultText { get; set; }
        public string SeverityText { get; set; }
        public string ResultDescription { get; set; }
        public string LegalForm { get; set; }
        public string LegalFormCode { get; set; }
        public string PrimaryAddressTerritoryOfficialName { get; set; }
        public string IncorporationYear { get; set; }
        public string ShareCapital_CapitalAmountUnitOfSize { get; set; }
        public string ShareCapital_CapitalAmountCurrencyISOAlpha3Code { get; set; }
        public string ShareCapital_CapitalAmount { get; set; }
        public string ShareCapital_CapitalType { get; set; }
        public string ShareCapital_StartDate { get; set; }
        public string ShareCapital_TypeCode { get; set; }
        public string OrganizationName { get; set; }
        public string TradeStyleName0 { get; set; }
        public string TradeStyleName1 { get; set; }
        public string TradeStyleName2 { get; set; }
        public string TradeStyleName3 { get; set; }
        public string TradeStyleName4 { get; set; }
        public string FormerOrganizationName { get; set; }
        public string TelecommunicationNumber { get; set; }
        public string InternationalDialingCode { get; set; }
        public string UnreachableIndicator { get; set; }
        public string Facsimile_TelecommunicationNumber { get; set; }
        public string Facsimile_InternationalDialingCode { get; set; }
        public string WebPageAddress0 { get; set; }
        public string WebPageAddress1 { get; set; }
        public string WebPageAddress2 { get; set; }
        public string WebPageAddress3 { get; set; }
        public string SmallBusinessIndicator { get; set; }
        public string FemaleOwnedIndicator { get; set; }
        public string LaborSurplusAreaIndicator { get; set; }
        public string EthnicityType { get; set; }
        public string EthnicityTypeCode { get; set; }
        public string MinorityOwnedIndicator { get; set; }
        public string IndividualEntityEmployee_TotalEmployeeQuantity { get; set; }
        public string IndividualEntityEmployee_Reliability { get; set; }
        public string IndividualEntityEmployee_ReliabilityCode { get; set; }
        public string ConsolidatedEmployee_TotalEmployeeQuantity { get; set; }
        public string ConsolidatedEmployee_Reliability { get; set; }
        public string ConsolidatedEmployee_ReliabilityCode { get; set; }
        public string ConsolidatedEmployee_EmployeeBasis { get; set; }
        public string ConsolidatedEmployee_EmployeeBasisCode { get; set; }
        public string ConsolidatedEmployee_EmployeeFiguresDate { get; set; }
        public string DUNSSelfRequestIndicator { get; set; }
        public string OrganizationSummary { get; set; }
        public string DUNSNumber { get; set; }
        public string LastUpdateDate { get; set; }
        public string TotalInquiriesCount { get; set; }
        public string MarketabilityIndicator { get; set; }
        public string TransferDUNSNumberRegistration_TransferDate { get; set; }
        public string TransferDUNSNumberRegistration_TransferReason { get; set; }
        public string TransferDUNSNumberRegistration_TransferReasonCode { get; set; }
        public string TransferDUNSNumberRegistration_TransferredFromDUNSNumber { get; set; }
        public string TransferDUNSNumberRegistration_TransferredToDUNSNumber { get; set; }
        public string DUNSSelfRequestDate { get; set; }
        public string SubjectHandling { get; set; }
        public string SubjectHandlingCode { get; set; }
        public string MostSeniorPrincipal_JobTitle { get; set; }
        public string MostSeniorPrincipal_CurrentManagementResponsibilityCode0 { get; set; }
        public string MostSeniorPrincipal_CurrentManagementResponsibility0 { get; set; }
        public string MostSeniorPrincipal_CurrentManagementResponsibilityCode1 { get; set; }
        public string MostSeniorPrincipal_CurrentManagementResponsibility1 { get; set; }
        public string MostSeniorPrincipal_CurrentManagementResponsibilityCode2 { get; set; }
        public string MostSeniorPrincipal_CurrentManagementResponsibility2 { get; set; }
        public string MostSeniorPrincipal_FirstName { get; set; }
        public string MostSeniorPrincipal_MiddleName { get; set; }
        public string MostSeniorPrincipal_LastName { get; set; }
        public string MostSeniorPrincipal_FullName { get; set; }
        public string MostSeniorPrincipal_NamePrefix { get; set; }
        public string MostSeniorPrincipal_NameSuffix { get; set; }
        public string MostSeniorPrincipal_PrincipalNameType { get; set; }
        public string MostSeniorPrincipal_PrincipalIdentificationNumber { get; set; }
        public string MostSeniorPrincipal_PrincipalIdentificationNumberType { get; set; }
        public string MostSeniorPrincipal_PrincipalIdentificationNumberTypeCode { get; set; }
        public string MostSeniorPrincipal_CurrentCompensationDate { get; set; }
        public string MostSeniorPrincipal_CompensationAmountCurrencyISOAlpha3Code0 { get; set; }
        public string MostSeniorPrincipal_CompensationAmount0 { get; set; }
        public string MostSeniorPrincipal_CompensationType0 { get; set; }
        public string MostSeniorPrincipal_CompensationTypeCode0 { get; set; }
        public string MostSeniorPrincipal_CompensationAmountCurrencyISOAlpha3Code1 { get; set; }
        public string MostSeniorPrincipal_CompensationAmount1 { get; set; }
        public string MostSeniorPrincipal_CompensationType1 { get; set; }
        public string MostSeniorPrincipal_CompensationTypeCode1 { get; set; }
        public string MostSeniorPrincipal_CompensationAmountCurrencyISOAlpha3Code2 { get; set; }
        public string MostSeniorPrincipal_CompensationAmount2 { get; set; }
        public string MostSeniorPrincipal_CompensationType2 { get; set; }
        public string MostSeniorPrincipal_CompensationTypeCode2 { get; set; }
        public string MostSeniorPrincipal_PrincipalAge { get; set; }
        public string MailingAddress_CountryISOAlpha2Code { get; set; }
        public string MailingAddress_UndeliverableIndicator { get; set; }
        public string MailingAddress_TerritoryAbbreviatedName { get; set; }
        public string MailingAddress_TerritoryOfficialName { get; set; }
        public string MailingAddress_CountyOfficialName { get; set; }
        public string MailingAddress_PostalCode { get; set; }
        public string MailingAddress_StreetAddressLine1 { get; set; }
        public string MailingAddress_StreetAddressLine2 { get; set; }
        public string MailingAddress_PrimaryTownName { get; set; }
        public string PrimaryAddress_PremisesFunction { get; set; }
        public string PrimaryAddress_PremisesFunctionCode { get; set; }
        public string PrimaryAddress_TerritoryAbbreviatedName { get; set; }
        public string PrimaryAddress_LongitudeMeasurement { get; set; }
        public string PrimaryAddress_RegisteredAddressIndicator { get; set; }
        public string PrimaryAddress_TerritoryOfficialName { get; set; }
        public string PrimaryAddress_CountyOfficialName { get; set; }
        public string PrimaryAddress_GeographicalPrecision { get; set; }
        public string PrimaryAddress_GeographicalPrecisionCode { get; set; }
        public string PrimaryAddress_PostalCode { get; set; }
        public string PrimaryAddress_ResidentialAddressIndicator { get; set; }
        public string PrimaryAddress_StreetAddressLine1 { get; set; }
        public string PrimaryAddress_StreetAddressLine2 { get; set; }
        public string PrimaryAddress_MetropolitanStatisticalAreaUSCensusCode { get; set; }
        public string PrimaryAddress_CountryISOAlpha2Code { get; set; }
        public string PrimaryAddress_CountryGroupName { get; set; }
        public string PrimaryAddress_AddressUsageTenureType { get; set; }
        public string PrimaryAddress_AddressUsageTenureTypeCode { get; set; }
        public string PrimaryAddress_PrimaryTownName { get; set; }
        public string PrimaryAddress_UndeliverableIndicator { get; set; }
        public string PrimaryAddress_PremisesAreaMeasurementReliability { get; set; }
        public string PrimaryAddress_PremisesAreaMeasurementReliabilityCode { get; set; }
        public string PrimaryAddress_PremisesAreaMeasurement { get; set; }
        public string PrimaryAddress_PremisesAreaMeasurementUnit { get; set; }
        public string PrimaryAddress_PremisesAreaMeasurementUnitCode { get; set; }
        public string PrimaryAddress_LatitudeMeasurement { get; set; }
        public string OrganizationDetail_ControlOwnershipType { get; set; }
        public string OrganizationDetail_ControlOwnershipTypeCode { get; set; }
        public string OrganizationDetail_ControlOwnershipDate { get; set; }
        public string OrganizationDetail_BoneyardOrganizationIndicator { get; set; }
        public string OrganizationDetail_OrganizationStartYear { get; set; }
        public string OrganizationDetail_OperatingStatus { get; set; }
        public string OrganizationDetail_OperatingStatusCode { get; set; }
        public string OrganizationDetail_StandaloneOrganizationIndicator { get; set; }
        public string OrganizationDetail_FranchiseOperationType { get; set; }
        public string OrganizationDetail_OperatingStatusComment { get; set; }
        public string LineOfBusiness { get; set; }
        public string PrimarySICCategory { get; set; }
        public string ExportIndicator { get; set; }
        public string ImportIndicator { get; set; }
        public string AgentIndicator { get; set; }
        public string OperationsText { get; set; }
        public string Assessment_HistoryRating { get; set; }
        public string Assessment_HistoryRatingCode { get; set; }
        public string CommercialCreditScore_MarketingRiskClass { get; set; }
        public string CommercialCreditScore_MarketingRiskClassCode { get; set; }
        public string Link_DomesticUltimateOrg_OrganizationName { get; set; }
        public string Link_DomesticUltimateOrg_PostalCode { get; set; }
        public string Link_DomesticUltimateOrg_TerritoryAbbreviatedName { get; set; }
        public string Link_DomesticUltimateOrg_TerritoryOfficialName { get; set; }
        public string Link_DomesticUltimateOrg_PrimaryTownName { get; set; }
        public string Link_DomesticUltimateOrg_StreetAddressLine1 { get; set; }
        public string Link_DomesticUltimateOrg_CountryISOAlpha2Code { get; set; }
        public string Link_DomesticUltimateOrg_DUNSNumber { get; set; }
        public string Link_LinkageSummary_GlobalUltimateFamilyTreeLinkageCount { get; set; }
        public string Link_GlobalUltimateOrg_OrganizationName { get; set; }
        public string Link_GlobalUltimateOrg_PostalCode { get; set; }
        public string Link_GlobalUltimateOrg_TerritoryAbbreviatedName { get; set; }
        public string Link_GlobalUltimateOrg_TerritoryOfficialName { get; set; }
        public string Link_GlobalUltimateOrg_PrimaryTownName { get; set; }
        public string Link_GlobalUltimateOrg_StreetAddressLine_LineText { get; set; }
        public string Link_GlobalUltimateOrg_CountryISOAlpha2Code { get; set; }
        public string LLink_GlobalUltimateOrg_DUNSNumber { get; set; }
        public string Link_HeadquartersOrg_OrganizationName { get; set; }
        public string Link_HeadquartersOrg_PostalCode { get; set; }
        public string Link_HeadquartersOrg_TerritoryAbbreviatedName { get; set; }
        public string Link_HeadquartersOrg_TerritoryOfficialName { get; set; }
        public string Link_HeadquartersOrg_PrimaryTownName { get; set; }
        public string Link_HeadquartersOrg_StreetAddressLine_LineText { get; set; }
        public string Link_HeadquartersOrg_CountryISOAlpha2Code { get; set; }
        public string Link_HeadquartersOrg_DUNSNumber { get; set; }
        public string Link_ParentOrg_OrganizationName { get; set; }
        public string Link_ParentOrg_PostalCode { get; set; }
        public string Link_ParentOrg_TerritoryAbbreviatedName { get; set; }
        public string Link_ParentOrg_TerritoryOfficialName { get; set; }
        public string Link_ParentOrg_PrimaryTownName { get; set; }
        public string Link_ParentOrg_StreetAddressLine_LineText { get; set; }
        public string Link_ParentOrg_CountryISOAlpha2Code { get; set; }
        public string Link_ParentOrg_DUNSNumber { get; set; }
        public string ThirdPartyAssessmentType0 { get; set; }
        public string ThirdPartyAssessmentValue0 { get; set; }
        public string ThirdPartyAssessmentType1 { get; set; }
        public string ThirdPartyAssessmentValue1 { get; set; }
        public string ThirdPartyAssessmentType2 { get; set; }
        public string ThirdPartyAssessmentValue2 { get; set; }
        public string ThirdPartyAssessmentType3 { get; set; }
        public string ThirdPartyAssessmentValue3 { get; set; }
        public string ThirdPartyAssessmentType4 { get; set; }
        public string ThirdPartyAssessmentValue4 { get; set; }
        public string FinancialAssetArticle_AssetType { get; set; }
        public string FinancialAssetArticle_AssetTypeCode { get; set; }
        public string FinancialAssetArticle_AssetClass { get; set; }
        public string FinancialAssetArticle_AssetClassCode { get; set; }
        public string FinancialAssetArticle_AssetArticleQuantity { get; set; }
        public string Banking_OrganizationName { get; set; }
        public string InquiryDetail_DNBProductID { get; set; }
        public string InquiryDetail_CountryISOAlpha2Code { get; set; }
        public string InquiryDetail_DUNSNumber { get; set; }
        public string ServiceVersionNumber { get; set; }

    }
}