//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBISCCMWeb.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BrandingLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BrandingLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SBISCCMWeb.LanguageResources.BrandingLang", typeof(BrandingLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you did not request to reset your password, please contact your Matchbook Services Administrator or our support desk at support@matchbookservices.com..
        /// </summary>
        public static string msgDandBResetPassword {
            get {
                return ResourceManager.GetString("msgDandBResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matchbook Services Support.
        /// </summary>
        public static string msgDandBSupport {
            get {
                return ResourceManager.GetString("msgDandBSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to continue, you must agree to the terms of the licensing agreement by checking &apos;I accept&apos; below..
        /// </summary>
        public static string msgDandBURL {
            get {
                return ResourceManager.GetString("msgDandBURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To activate this feature or to learn more, please contact your Account executive.
        /// </summary>
        public static string msgDNBFeature {
            get {
                return ResourceManager.GetString("msgDNBFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matchbook Services Support.
        /// </summary>
        public static string msgMatchbookSupport {
            get {
                return ResourceManager.GetString("msgMatchbookSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matchbook Helpdesk ticket created.
        /// </summary>
        public static string msgMatchbookTicketCreated {
            get {
                return ResourceManager.GetString("msgMatchbookTicketCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.matchbookservices.com/license.
        /// </summary>
        public static string msgMatchbookURL {
            get {
                return ResourceManager.GetString("msgMatchbookURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To activate this feature or to learn more, please contact your Account executive or email us at sales@matchbookservices.com.
        /// </summary>
        public static string msgMBFeature {
            get {
                return ResourceManager.GetString("msgMBFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to continue, you must agree to the terms of the licensing agreement by checking &apos;I accept&apos; below. The licensing agreement is available at.
        /// </summary>
        public static string msgValidEULAText {
            get {
                return ResourceManager.GetString("msgValidEULAText", resourceCulture);
            }
        }
    }
}
