//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBISCCMWeb.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommandLineLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandLineLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SBISCCMWeb.LanguageResources.CommandLineLang", typeof(CommandLineLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Mapping.
        /// </summary>
        public static string hdrColumnMapping {
            get {
                return ResourceManager.GetString("hdrColumnMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Line EXE Download.
        /// </summary>
        public static string hdrCommandLineEXEDownload {
            get {
                return ResourceManager.GetString("hdrCommandLineEXEDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Configuration.
        /// </summary>
        public static string hdrDownloadConfiguration {
            get {
                return ResourceManager.GetString("hdrDownloadConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Configuration List.
        /// </summary>
        public static string hdrDownloadConfigurationList {
            get {
                return ResourceManager.GetString("hdrDownloadConfigurationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linux Setup.
        /// </summary>
        public static string hdrLinuxSetup {
            get {
                return ResourceManager.GetString("hdrLinuxSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Configuration List.
        /// </summary>
        public static string hdrUploadConfigurationList {
            get {
                return ResourceManager.GetString("hdrUploadConfigurationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Configuration Mapping.
        /// </summary>
        public static string hdrUploadConfigurationMapping {
            get {
                return ResourceManager.GetString("hdrUploadConfigurationMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Setup.
        /// </summary>
        public static string hdrWindowsSetup {
            get {
                return ResourceManager.GetString("hdrWindowsSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string lbEdit {
            get {
                return ResourceManager.GetString("lbEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string lblAdd {
            get {
                return ResourceManager.GetString("lblAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add DateTime as File prefix.
        /// </summary>
        public static string lblAddDateTimeasFileprefix {
            get {
                return ResourceManager.GetString("lblAddDateTimeasFileprefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Column.
        /// </summary>
        public static string lblAdditionalColumn {
            get {
                return ResourceManager.GetString("lblAdditionalColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Fields.
        /// </summary>
        public static string lblAdditionalFields {
            get {
                return ResourceManager.GetString("lblAdditionalFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add optional File Prefix.
        /// </summary>
        public static string lblAddoptionalFilePrefix {
            get {
                return ResourceManager.GetString("lblAddoptionalFilePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .xls,.xlsx.
        /// </summary>
        public static string lblAllowedFormats {
            get {
                return ResourceManager.GetString("lblAllowedFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append DateTime to file name.
        /// </summary>
        public static string lblAppendDateTimetofilename {
            get {
                return ResourceManager.GetString("lblAppendDateTimetofilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Text Qualifier To All.
        /// </summary>
        public static string lblApplyTextQualifierToAll {
            get {
                return ResourceManager.GetString("lblApplyTextQualifierToAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigurationName.
        /// </summary>
        public static string lblConfigurationName {
            get {
                return ResourceManager.GetString("lblConfigurationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV.
        /// </summary>
        public static string lblCSV {
            get {
                return ResourceManager.GetString("lblCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Delimiter.
        /// </summary>
        public static string lblCustomDelimiter {
            get {
                return ResourceManager.GetString("lblCustomDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string lblDelete {
            get {
                return ResourceManager.GetString("lblDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DownloadFormat.
        /// </summary>
        public static string lblDownloadFormat {
            get {
                return ResourceManager.GetString("lblDownloadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g..
        /// </summary>
        public static string lblExample {
            get {
                return ResourceManager.GetString("lblExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel.
        /// </summary>
        public static string lblExcel {
            get {
                return ResourceManager.GetString("lblExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileFormat.
        /// </summary>
        public static string lblFileFormat {
            get {
                return ResourceManager.GetString("lblFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format Value.
        /// </summary>
        public static string lblFormatValue {
            get {
                return ResourceManager.GetString("lblFormatValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Data.
        /// </summary>
        public static string lblImportData {
            get {
                return ResourceManager.GetString("lblImportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImportType.
        /// </summary>
        public static string lblImportType {
            get {
                return ResourceManager.GetString("lblImportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Header.
        /// </summary>
        public static string lblInputHeader {
            get {
                return ResourceManager.GetString("lblInputHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Default.
        /// </summary>
        public static string lblIsDefault {
            get {
                return ResourceManager.GetString("lblIsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOBTag.
        /// </summary>
        public static string lblLOBTag {
            get {
                return ResourceManager.GetString("lblLOBTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark As Exported.
        /// </summary>
        public static string lblMarkAsExported {
            get {
                return ResourceManager.GetString("lblMarkAsExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatchOutPut.
        /// </summary>
        public static string lblMatchOutPut {
            get {
                return ResourceManager.GetString("lblMatchOutPut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string lblNext {
            get {
                return ResourceManager.GetString("lblNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output format.
        /// </summary>
        public static string lblOutputformat {
            get {
                return ResourceManager.GetString("lblOutputformat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string lblPrevious {
            get {
                return ResourceManager.GetString("lblPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select API Layer..
        /// </summary>
        public static string lblRequiredAPILayer {
            get {
                return ResourceManager.GetString("lblRequiredAPILayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill Configuration Name..
        /// </summary>
        public static string lblRequiredConfigurationName {
            get {
                return ResourceManager.GetString("lblRequiredConfigurationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select file..
        /// </summary>
        public static string lblRequiredFile {
            get {
                return ResourceManager.GetString("lblRequiredFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Output Type..
        /// </summary>
        public static string lblRequiredOutputType {
            get {
                return ResourceManager.GetString("lblRequiredOutputType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Provider Type..
        /// </summary>
        public static string lblRequiredProviderType {
            get {
                return ResourceManager.GetString("lblRequiredProviderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RHEL 6.
        /// </summary>
        public static string lblRHEL6 {
            get {
                return ResourceManager.GetString("lblRHEL6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RHEL 7.
        /// </summary>
        public static string lblRHEL7 {
            get {
                return ResourceManager.GetString("lblRHEL7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Configuration Name.
        /// </summary>
        public static string lblSelectConfigurationName {
            get {
                return ResourceManager.GetString("lblSelectConfigurationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File.
        /// </summary>
        public static string lblSelectFile {
            get {
                return ResourceManager.GetString("lblSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File Format.
        /// </summary>
        public static string lblSelectFileFormat {
            get {
                return ResourceManager.GetString("lblSelectFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Filters.
        /// </summary>
        public static string lblSelectFilters {
            get {
                return ResourceManager.GetString("lblSelectFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Import Type.
        /// </summary>
        public static string lblSelectImportType {
            get {
                return ResourceManager.GetString("lblSelectImportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        public static string lblSelectLanguage {
            get {
                return ResourceManager.GetString("lblSelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Provider.
        /// </summary>
        public static string lblSelectProvider {
            get {
                return ResourceManager.GetString("lblSelectProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string lblSubmit {
            get {
                return ResourceManager.GetString("lblSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Column.
        /// </summary>
        public static string lblTableColumn {
            get {
                return ResourceManager.GetString("lblTableColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab Separated.
        /// </summary>
        public static string lblTabSeparated {
            get {
                return ResourceManager.GetString("lblTabSeparated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string lblTag {
            get {
                return ResourceManager.GetString("lblTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string lblUpdate {
            get {
                return ResourceManager.GetString("lblUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload File.
        /// </summary>
        public static string lblUploadFile {
            get {
                return ResourceManager.GetString("lblUploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to win32.
        /// </summary>
        public static string lblwin32 {
            get {
                return ResourceManager.GetString("lblwin32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to win64.
        /// </summary>
        public static string lblwin64 {
            get {
                return ResourceManager.GetString("lblwin64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only formats allowed are :.
        /// </summary>
        public static string msgFileFormatsAllowed {
            get {
                return ResourceManager.GetString("msgFileFormatsAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Name.
        /// </summary>
        public static string placeholderConfName {
            get {
                return ResourceManager.GetString("placeholderConfName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Command Download Mapping.
        /// </summary>
        public static string titleAddCommandDownloadMapping {
            get {
                return ResourceManager.GetString("titleAddCommandDownloadMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Command Mapping.
        /// </summary>
        public static string titleAddCommandMapping {
            get {
                return ResourceManager.GetString("titleAddCommandMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV.
        /// </summary>
        public static string titleCSV {
            get {
                return ResourceManager.GetString("titleCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Delimiter.
        /// </summary>
        public static string titleCustomDelimiter {
            get {
                return ResourceManager.GetString("titleCustomDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel.
        /// </summary>
        public static string titleExcel {
            get {
                return ResourceManager.GetString("titleExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab Separated.
        /// </summary>
        public static string titleTabSeparated {
            get {
                return ResourceManager.GetString("titleTabSeparated", resourceCulture);
            }
        }
    }
}
