//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBISCCMWeb.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonMessagesLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonMessagesLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SBISCCMWeb.LanguageResources.CommonMessagesLang", typeof(CommonMessagesLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Data Queue.
        /// </summary>
        public static string lblActiveDataQueue {
            get {
                return ResourceManager.GetString("lblActiveDataQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files.
        /// </summary>
        public static string lblAllFiles {
            get {
                return ResourceManager.GetString("lblAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any.
        /// </summary>
        public static string lblAny {
            get {
                return ResourceManager.GetString("lblAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Beneficiary Details.
        /// </summary>
        public static string lblBenificiaryDetails {
            get {
                return ResourceManager.GetString("lblBenificiaryDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string lblBrowse {
            get {
                return ResourceManager.GetString("lblBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00: Business Name.
        /// </summary>
        public static string lblBusinessName {
            get {
                return ResourceManager.GetString("lblBusinessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleanse, Match &amp; Enrichment.
        /// </summary>
        public static string lblCleanseMatch {
            get {
                return ResourceManager.GetString("lblCleanseMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string lblCompany {
            get {
                return ResourceManager.GetString("lblCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanyTree.
        /// </summary>
        public static string lblCompanyTree {
            get {
                return ResourceManager.GetString("lblCompanyTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string lblConfirm {
            get {
                return ResourceManager.GetString("lblConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D&amp;B.
        /// </summary>
        public static string lblDAndB {
            get {
                return ResourceManager.GetString("lblDAndB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F: Different.
        /// </summary>
        public static string lblDifferent {
            get {
                return ResourceManager.GetString("lblDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dun &amp; Bradstreet.
        /// </summary>
        public static string lblDunBradstreet {
            get {
                return ResourceManager.GetString("lblDunBradstreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrichment Only.
        /// </summary>
        public static string lblEnrichment {
            get {
                return ResourceManager.GetString("lblEnrichment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        public static string lblFalse {
            get {
                return ResourceManager.GetString("lblFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmographics.
        /// </summary>
        public static string lblFirmographics {
            get {
                return ResourceManager.GetString("lblFirmographics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matchbook.
        /// </summary>
        public static string lblMatchbook {
            get {
                return ResourceManager.GetString("lblMatchbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Output.
        /// </summary>
        public static string lblMatchOutput {
            get {
                return ResourceManager.GetString("lblMatchOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z: Missing Input.
        /// </summary>
        public static string lblMissingInput {
            get {
                return ResourceManager.GetString("lblMissingInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Files.
        /// </summary>
        public static string lblMyFiles {
            get {
                return ResourceManager.GetString("lblMyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X: No Data.
        /// </summary>
        public static string lblNoData {
            get {
                return ResourceManager.GetString("lblNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string lblNone {
            get {
                return ResourceManager.GetString("lblNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orb Cleanse, Match &amp; Enrichment.
        /// </summary>
        public static string lblOrbCleanseMatch {
            get {
                return ResourceManager.GetString("lblOrbCleanseMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orb Enrichment Only.
        /// </summary>
        public static string lblOrbEnrichment {
            get {
                return ResourceManager.GetString("lblOrbEnrichment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orb Intelligence.
        /// </summary>
        public static string lblOrbIntelligence {
            get {
                return ResourceManager.GetString("lblOrbIntelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01: Other Name.
        /// </summary>
        public static string lblOtherName {
            get {
                return ResourceManager.GetString("lblOtherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A: Same.
        /// </summary>
        public static string lblSame {
            get {
                return ResourceManager.GetString("lblSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select AcceptedBy.
        /// </summary>
        public static string lblSelectAcceptedBy {
            get {
                return ResourceManager.GetString("lblSelectAcceptedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Api Layer.
        /// </summary>
        public static string lblSelectApiLayer {
            get {
                return ResourceManager.GetString("lblSelectApiLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Confidence Code.
        /// </summary>
        public static string lblSelectConfidenceCode {
            get {
                return ResourceManager.GetString("lblSelectConfidenceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Country.
        /// </summary>
        public static string lblSelectCountry {
            get {
                return ResourceManager.GetString("lblSelectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Country Group.
        /// </summary>
        public static string lblSelectCountryGroup {
            get {
                return ResourceManager.GetString("lblSelectCountryGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Import Process.
        /// </summary>
        public static string lblSelectImportProcess {
            get {
                return ResourceManager.GetString("lblSelectImportProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Import Process (Optional).
        /// </summary>
        public static string lblSelectImportProcessOptional {
            get {
                return ResourceManager.GetString("lblSelectImportProcessOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Industry.
        /// </summary>
        public static string lblSelectIndustry {
            get {
                return ResourceManager.GetString("lblSelectIndustry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        public static string lblSelectLanguage {
            get {
                return ResourceManager.GetString("lblSelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select LOB Tag.
        /// </summary>
        public static string lblSelectLOBTag {
            get {
                return ResourceManager.GetString("lblSelectLOBTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select LOB Tag (Optional).
        /// </summary>
        public static string lblSelectLOBTagOptional {
            get {
                return ResourceManager.GetString("lblSelectLOBTagOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select NAICS Code.
        /// </summary>
        public static string lblSelectNAICSCode {
            get {
                return ResourceManager.GetString("lblSelectNAICSCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Priority.
        /// </summary>
        public static string lblSelectPriority {
            get {
                return ResourceManager.GetString("lblSelectPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Product Layer.
        /// </summary>
        public static string lblSelectProductLayer {
            get {
                return ResourceManager.GetString("lblSelectProductLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Ranking.
        /// </summary>
        public static string lblSelectRanking {
            get {
                return ResourceManager.GetString("lblSelectRanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Security Question.
        /// </summary>
        public static string lblSelectSecurityQuestion {
            get {
                return ResourceManager.GetString("lblSelectSecurityQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select SIC Code.
        /// </summary>
        public static string lblSelectSICCode {
            get {
                return ResourceManager.GetString("lblSelectSICCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select State.
        /// </summary>
        public static string lblSelectState {
            get {
                return ResourceManager.GetString("lblSelectState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Tag.
        /// </summary>
        public static string lblSelectTag {
            get {
                return ResourceManager.GetString("lblSelectTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Tags (Optional).
        /// </summary>
        public static string lblSelectTagsOptional {
            get {
                return ResourceManager.GetString("lblSelectTagsOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Tag type.
        /// </summary>
        public static string lblSelectTagtype {
            get {
                return ResourceManager.GetString("lblSelectTagtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Technologies.
        /// </summary>
        public static string lblSelectTechnologies {
            get {
                return ResourceManager.GetString("lblSelectTechnologies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Technologies Categories.
        /// </summary>
        public static string lblSelectTechnologiesCategories {
            get {
                return ResourceManager.GetString("lblSelectTechnologiesCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Ticker.
        /// </summary>
        public static string lblSelectTicker {
            get {
                return ResourceManager.GetString("lblSelectTicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Type.
        /// </summary>
        public static string lblSelectType {
            get {
                return ResourceManager.GetString("lblSelectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B: Similar.
        /// </summary>
        public static string lblSimilar {
            get {
                return ResourceManager.GetString("lblSimilar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SrcRecordId.
        /// </summary>
        public static string lblSrcRecordId {
            get {
                return ResourceManager.GetString("lblSrcRecordId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string lblState {
            get {
                return ResourceManager.GetString("lblState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        public static string lblTrue {
            get {
                return ResourceManager.GetString("lblTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Ahead.
        /// </summary>
        public static string lblTypeAhead {
            get {
                return ResourceManager.GetString("lblTypeAhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is temporarily suspended..
        /// </summary>
        public static string msgAccountSuspended {
            get {
                return ResourceManager.GetString("msgAccountSuspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is temporarily suspended. Please contact administrator to active account..
        /// </summary>
        public static string msgAccountSuspendedTemporarily {
            get {
                return ResourceManager.GetString("msgAccountSuspendedTemporarily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is temporarily suspended.
        /// </summary>
        public static string msgAccountTemporarilySuspended {
            get {
                return ResourceManager.GetString("msgAccountTemporarilySuspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Users.
        /// </summary>
        public static string msgActiveUsers {
            get {
                return ResourceManager.GetString("msgActiveUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add filter.
        /// </summary>
        public static string msgAddFilter {
            get {
                return ResourceManager.GetString("msgAddFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add match as a new company.
        /// </summary>
        public static string msgaddMatchAsCompany {
            get {
                return ResourceManager.GetString("msgaddMatchAsCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Tags (Optional).
        /// </summary>
        public static string msgAddTag {
            get {
                return ResourceManager.GetString("msgAddTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only formats allowed are :jpeg, jpg, png, gif, bmp.
        /// </summary>
        public static string msgAllowedFormats {
            get {
                return ResourceManager.GetString("msgAllowedFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only formats allowed are .xls and .xlsx.
        /// </summary>
        public static string msgAllowedOnlyExcel {
            get {
                return ResourceManager.GetString("msgAllowedOnlyExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not authorized to make this change..
        /// </summary>
        public static string msgAuthError {
            get {
                return ResourceManager.GetString("msgAuthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only formats allowed are :xls,xlsx.
        /// </summary>
        public static string msgCommanChechExcelFile {
            get {
                return ResourceManager.GetString("msgCommanChechExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data deleted successfully.
        /// </summary>
        public static string msgCommanDeleteMessage {
            get {
                return ResourceManager.GetString("msgCommanDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to import the data into the database. Please try again or contact Matchbook Services support..
        /// </summary>
        public static string msgCommanEnableFileImport {
            get {
                return ResourceManager.GetString("msgCommanEnableFileImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred. Please try again.
        /// </summary>
        public static string msgCommanErrorMessage {
            get {
                return ResourceManager.GetString("msgCommanErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is Empty..
        /// </summary>
        public static string msgCommanFileEmpty {
            get {
                return ResourceManager.GetString("msgCommanFileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data created successfully.
        /// </summary>
        public static string msgCommanInsertMessage {
            get {
                return ResourceManager.GetString("msgCommanInsertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data updated successfully.
        /// </summary>
        public static string msgCommanUpdateMessage {
            get {
                return ResourceManager.GetString("msgCommanUpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data rejected successfully.
        /// </summary>
        public static string msgDataRejected {
            get {
                return ResourceManager.GetString("msgDataRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete session filter?.
        /// </summary>
        public static string msgDeleteSessionFilter {
            get {
                return ResourceManager.GetString("msgDeleteSessionFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid file name..
        /// </summary>
        public static string msgEnterValidName {
            get {
                return ResourceManager.GetString("msgEnterValidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred..
        /// </summary>
        public static string msgErrorOccurred {
            get {
                return ResourceManager.GetString("msgErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exist.
        /// </summary>
        public static string msgExist {
            get {
                return ResourceManager.GetString("msgExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExistsFail.
        /// </summary>
        public static string msgExistsFail {
            get {
                return ResourceManager.GetString("msgExistsFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fail.
        /// </summary>
        public static string msgFail {
            get {
                return ResourceManager.GetString("msgFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failer.
        /// </summary>
        public static string msgFailer {
            get {
                return ResourceManager.GetString("msgFailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not specified a file..
        /// </summary>
        public static string msgFileNotSpecified {
            get {
                return ResourceManager.GetString("msgFileNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your file(s).
        /// </summary>
        public static string msgFiles {
            get {
                return ResourceManager.GetString("msgFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to are ready for the download..
        /// </summary>
        public static string msgFilesReadyToDownload {
            get {
                return ResourceManager.GetString("msgFilesReadyToDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File uploaded successfully.
        /// </summary>
        public static string msgFileUploaded {
            get {
                return ResourceManager.GetString("msgFileUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill proper information..
        /// </summary>
        public static string msgInvadilState {
            get {
                return ResourceManager.GetString("msgInvadilState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not valid..
        /// </summary>
        public static string msgInvalidEmail {
            get {
                return ResourceManager.GetString("msgInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select proper file..
        /// </summary>
        public static string msgInvalidFile {
            get {
                return ResourceManager.GetString("msgInvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid template for the selected file..
        /// </summary>
        public static string msgInvalidTemplate {
            get {
                return ResourceManager.GetString("msgInvalidTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicode format is not valid for selected file with template..
        /// </summary>
        public static string msgInvalidUnicodeFormat {
            get {
                return ResourceManager.GetString("msgInvalidUnicodeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user..
        /// </summary>
        public static string msgInvalidUser {
            get {
                return ResourceManager.GetString("msgInvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password..
        /// </summary>
        public static string msgInvalidUsernamePassword {
            get {
                return ResourceManager.GetString("msgInvalidUsernamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investigate Record.
        /// </summary>
        public static string msgInvestigateRecord {
            get {
                return ResourceManager.GetString("msgInvestigateRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your requests are in queue, it will take a while to submit all selected Investigation. Please check Investigation reports for status of all requests in few minutes..
        /// </summary>
        public static string msgMultipleInvestigationSubmit {
            get {
                return ResourceManager.GetString("msgMultipleInvestigationSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string msgNext {
            get {
                return ResourceManager.GetString("msgNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available..
        /// </summary>
        public static string msgNoDataAvailable {
            get {
                return ResourceManager.GetString("msgNoDataAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no data available in system for file..
        /// </summary>
        public static string msgNoDataInSystem {
            get {
                return ResourceManager.GetString("msgNoDataInSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no default key set for build a list..
        /// </summary>
        public static string msgNoDefaultKeyForBuildList {
            get {
                return ResourceManager.GetString("msgNoDefaultKeyForBuildList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no default key set for single entity search..
        /// </summary>
        public static string msgNoDefaultKeyForSearch {
            get {
                return ResourceManager.GetString("msgNoDefaultKeyForSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total 0 records are affected, are you sure you want to continue ?.
        /// </summary>
        public static string msgNoRecords {
            get {
                return ResourceManager.GetString("msgNoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results match.
        /// </summary>
        public static string msgNoResultsMatch {
            get {
                return ResourceManager.GetString("msgNoResultsMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotExist.
        /// </summary>
        public static string msgNotExist {
            get {
                return ResourceManager.GetString("msgNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops, nothing found!.
        /// </summary>
        public static string msgNothingFound {
            get {
                return ResourceManager.GetString("msgNothingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to move..
        /// </summary>
        public static string msgNothingToMove {
            get {
                return ResourceManager.GetString("msgNothingToMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Dismiss successfully..
        /// </summary>
        public static string msgNotificationDismissed {
            get {
                return ResourceManager.GetString("msgNotificationDismissed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Size.
        /// </summary>
        public static string msgPageSize {
            get {
                return ResourceManager.GetString("msgPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Reset Successfully..
        /// </summary>
        public static string msgPasswordReset {
            get {
                return ResourceManager.GetString("msgPasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string msgPrevious {
            get {
                return ResourceManager.GetString("msgPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purge Record.
        /// </summary>
        public static string msgPurgeRecord {
            get {
                return ResourceManager.GetString("msgPurgeRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to records are affected, are you sure you want to continue ?.
        /// </summary>
        public static string msgRecordsAffected {
            get {
                return ResourceManager.GetString("msgRecordsAffected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Match Record.
        /// </summary>
        public static string msgReMatchRecord {
            get {
                return ResourceManager.GetString("msgReMatchRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests submitted successfully..
        /// </summary>
        public static string msgRequestSubmitted {
            get {
                return ResourceManager.GetString("msgRequestSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter email address and set valid password..
        /// </summary>
        public static string msgRequiredEmail {
            get {
                return ResourceManager.GetString("msgRequiredEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter file name..
        /// </summary>
        public static string msgRequiredFileName {
            get {
                return ResourceManager.GetString("msgRequiredFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resert successfully.
        /// </summary>
        public static string msgResetSuccessfully {
            get {
                return ResourceManager.GetString("msgResetSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occurred. Please contact matchbookservices or create helpdesk ticket..
        /// </summary>
        public static string msgResponseErroeMessage {
            get {
                return ResourceManager.GetString("msgResponseErroeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Credential not set for monitoring.
        /// </summary>
        public static string msgSetDefaultCredentialForMonitoring {
            get {
                return ResourceManager.GetString("msgSetDefaultCredentialForMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong! Error Occured..
        /// </summary>
        public static string msgSomethingWentWrong {
            get {
                return ResourceManager.GetString("msgSomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong! Please try again later..
        /// </summary>
        public static string msgSomethingWrong {
            get {
                return ResourceManager.GetString("msgSomethingWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string msgSuccess {
            get {
                return ResourceManager.GetString("msgSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to are you sure you want to continue ?.
        /// </summary>
        public static string msgSureWantToContinue {
            get {
                return ResourceManager.GetString("msgSureWantToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template saved successfully..
        /// </summary>
        public static string msgTemplateSaved {
            get {
                return ResourceManager.GetString("msgTemplateSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template updated successfully..
        /// </summary>
        public static string msgTemplateUpdated {
            get {
                return ResourceManager.GetString("msgTemplateUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string msgTotal {
            get {
                return ResourceManager.GetString("msgTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License updated. Please note that users will need to log out and log back into the application before these changes can be applied.
        /// </summary>
        public static string msgUpdateLicance {
            get {
                return ResourceManager.GetString("msgUpdateLicance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is already logged in at another browser..
        /// </summary>
        public static string msgUserAlreadyLoggedIn {
            get {
                return ResourceManager.GetString("msgUserAlreadyLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is already logged in at another location..
        /// </summary>
        public static string msgUserAlreadyLoggedInAnotherLocation {
            get {
                return ResourceManager.GetString("msgUserAlreadyLoggedInAnotherLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter only alphanumeric,hyphen or underscore.
        /// </summary>
        public static string msgValidCharacters {
            get {
                return ResourceManager.GetString("msgValidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , are you sure you want to continue ?.
        /// </summary>
        public static string msgWantToContiune {
            get {
                return ResourceManager.GetString("msgWantToContiune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wrongFormat.
        /// </summary>
        public static string msgWrongFormat {
            get {
                return ResourceManager.GetString("msgWrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total 0 will be deleted, are you sure you want to continue ?.
        /// </summary>
        public static string msgZeroDeleted {
            get {
                return ResourceManager.GetString("msgZeroDeleted", resourceCulture);
            }
        }
    }
}
