//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBISCCMWeb.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LayoutLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LayoutLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SBISCCMWeb.LanguageResources.LayoutLang", typeof(LayoutLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address1.
        /// </summary>
        public static string lblAddress1 {
            get {
                return ResourceManager.GetString("lblAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address2.
        /// </summary>
        public static string lblAddress2 {
            get {
                return ResourceManager.GetString("lblAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string lblCity {
            get {
                return ResourceManager.GetString("lblCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string lblCompany {
            get {
                return ResourceManager.GetString("lblCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string lblCountry {
            get {
                return ResourceManager.GetString("lblCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D&amp;B.
        /// </summary>
        public static string lblDAndB {
            get {
                return ResourceManager.GetString("lblDAndB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send us feedback.
        /// </summary>
        public static string lblFeedback {
            get {
                return ResourceManager.GetString("lblFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you satisfied with your experience?.
        /// </summary>
        public static string lblFeedbackExperience {
            get {
                return ResourceManager.GetString("lblFeedbackExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string lblLanguage {
            get {
                return ResourceManager.GetString("lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to licensing agreement.
        /// </summary>
        public static string lblLicensingAgreement {
            get {
                return ResourceManager.GetString("lblLicensingAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string lblLogOff {
            get {
                return ResourceManager.GetString("lblLogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string lblMessage {
            get {
                return ResourceManager.GetString("lblMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No notifications are available.
        /// </summary>
        public static string lblNoNotificationsMessage {
            get {
                return ResourceManager.GetString("lblNoNotificationsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string lblNotifications {
            get {
                return ResourceManager.GetString("lblNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orb.
        /// </summary>
        public static string lblOrb {
            get {
                return ResourceManager.GetString("lblOrb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orb Intelligence.
        /// </summary>
        public static string lblOrbIntelligence {
            get {
                return ResourceManager.GetString("lblOrbIntelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string lblPhone {
            get {
                return ResourceManager.GetString("lblPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use of this portal is governed by the terms of Dun &amp; Bradstreet.
        /// </summary>
        public static string lblPortalDunAndBradstreet {
            get {
                return ResourceManager.GetString("lblPortalDunAndBradstreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use of this portal is governed by the terms of the.
        /// </summary>
        public static string lblPortalMatchbook {
            get {
                return ResourceManager.GetString("lblPortalMatchbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string lblPostalCode {
            get {
                return ResourceManager.GetString("lblPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while processing....
        /// </summary>
        public static string lblProcessing {
            get {
                return ResourceManager.GetString("lblProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Search.
        /// </summary>
        public static string lblQuickSearch {
            get {
                return ResourceManager.GetString("lblQuickSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill Company.
        /// </summary>
        public static string lblRequiredCompany {
            get {
                return ResourceManager.GetString("lblRequiredCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Country.
        /// </summary>
        public static string lblRequiredCountry {
            get {
                return ResourceManager.GetString("lblRequiredCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Feedback message is required..
        /// </summary>
        public static string lblRequiredFeedbackMessage {
            get {
                return ResourceManager.GetString("lblRequiredFeedbackMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Feedback type is required..
        /// </summary>
        public static string lblRequiredFeedbackType {
            get {
                return ResourceManager.GetString("lblRequiredFeedbackType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Data.
        /// </summary>
        public static string lblSearchData {
            get {
                return ResourceManager.GetString("lblSearchData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See All.
        /// </summary>
        public static string lblSeeAll {
            get {
                return ResourceManager.GetString("lblSeeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State/Territory.
        /// </summary>
        public static string lblStateTerritory {
            get {
                return ResourceManager.GetString("lblStateTerritory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit feedback.
        /// </summary>
        public static string lblSubmitfeedback {
            get {
                return ResourceManager.GetString("lblSubmitfeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Role.
        /// </summary>
        public static string lblUserRole {
            get {
                return ResourceManager.GetString("lblUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell us about your experience....
        /// </summary>
        public static string placeholderFeedbackExperience {
            get {
                return ResourceManager.GetString("placeholderFeedbackExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse Menu.
        /// </summary>
        public static string titleCollapseMenu {
            get {
                return ResourceManager.GetString("titleCollapseMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss Notification.
        /// </summary>
        public static string titleDismissNotification {
            get {
                return ResourceManager.GetString("titleDismissNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string titleFeedback {
            get {
                return ResourceManager.GetString("titleFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Desk.
        /// </summary>
        public static string titleHelpDesk {
            get {
                return ResourceManager.GetString("titleHelpDesk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string titleManage {
            get {
                return ResourceManager.GetString("titleManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative.
        /// </summary>
        public static string titleNegative {
            get {
                return ResourceManager.GetString("titleNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive.
        /// </summary>
        public static string titlePositive {
            get {
                return ResourceManager.GetString("titlePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Search.
        /// </summary>
        public static string titleQuickSearch {
            get {
                return ResourceManager.GetString("titleQuickSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Dashboard.
        /// </summary>
        public static string titleRefreshDashboard {
            get {
                return ResourceManager.GetString("titleRefreshDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string titleSignOut {
            get {
                return ResourceManager.GetString("titleSignOut", resourceCulture);
            }
        }
    }
}
