//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBISCCMWeb.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SiteMapLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SiteMapLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SBISCCMWeb.LanguageResources.SiteMapLang", typeof(SiteMapLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve Match Data.
        /// </summary>
        public static string lblApproveMatchData {
            get {
                return ResourceManager.GetString("lblApproveMatchData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Reports.
        /// </summary>
        public static string lblBaseReports {
            get {
                return ResourceManager.GetString("lblBaseReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build A List.
        /// </summary>
        public static string lblBuildAList {
            get {
                return ResourceManager.GetString("lblBuildAList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean Data.
        /// </summary>
        public static string lblCleanData {
            get {
                return ResourceManager.GetString("lblCleanData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D&amp;B.
        /// </summary>
        public static string lblDandB {
            get {
                return ResourceManager.GetString("lblDandB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string lblDashboard {
            get {
                return ResourceManager.GetString("lblDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Stewardship.
        /// </summary>
        public static string lblDataStewardship {
            get {
                return ResourceManager.GetString("lblDataStewardship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Data.
        /// </summary>
        public static string lblExportData {
            get {
                return ResourceManager.GetString("lblExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Desk.
        /// </summary>
        public static string lblHelpDesk {
            get {
                return ResourceManager.GetString("lblHelpDesk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string lblHome {
            get {
                return ResourceManager.GetString("lblHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Data.
        /// </summary>
        public static string lblImportData {
            get {
                return ResourceManager.GetString("lblImportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Records.
        /// </summary>
        public static string lblInputRecords {
            get {
                return ResourceManager.GetString("lblInputRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investigation Report.
        /// </summary>
        public static string lblInvestigationReport {
            get {
                return ResourceManager.GetString("lblInvestigationReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Family Tree (BETA).
        /// </summary>
        public static string lblManageFamilyTree {
            get {
                return ResourceManager.GetString("lblManageFamilyTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Data.
        /// </summary>
        public static string lblMatchData {
            get {
                return ResourceManager.GetString("lblMatchData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orb Intelligence.
        /// </summary>
        public static string lblOrbIntelligence {
            get {
                return ResourceManager.GetString("lblOrbIntelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal.
        /// </summary>
        public static string lblPortal {
            get {
                return ResourceManager.GetString("lblPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Matched Data (BETA).
        /// </summary>
        public static string lblPreviewMatchedData {
            get {
                return ResourceManager.GetString("lblPreviewMatchedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prospecting.
        /// </summary>
        public static string lblProspecting {
            get {
                return ResourceManager.GetString("lblProspecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string lblReports {
            get {
                return ResourceManager.GetString("lblReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iResearch Investigation.
        /// </summary>
        public static string lblResearchInvestigation {
            get {
                return ResourceManager.GetString("lblResearchInvestigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Match Candidates.
        /// </summary>
        public static string lblReviewMatchCandidates {
            get {
                return ResourceManager.GetString("lblReviewMatchCandidates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Data.
        /// </summary>
        public static string lblSearchData {
            get {
                return ResourceManager.GetString("lblSearchData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string lblSettings {
            get {
                return ResourceManager.GetString("lblSettings", resourceCulture);
            }
        }
    }
}
