//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBISCCMWeb.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TicketLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TicketLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SBISCCMWeb.LanguageResources.TicketLang", typeof(TicketLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Ticket.
        /// </summary>
        public static string hdrCreateTicket {
            get {
                return ResourceManager.GetString("hdrCreateTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Ticket.
        /// </summary>
        public static string hdrEditTicket {
            get {
                return ResourceManager.GetString("hdrEditTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Tickets.
        /// </summary>
        public static string hdrMyTickets {
            get {
                return ResourceManager.GetString("hdrMyTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket History.
        /// </summary>
        public static string hdrTicketHistory {
            get {
                return ResourceManager.GetString("hdrTicketHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Ticket.
        /// </summary>
        public static string lblAddTicket {
            get {
                return ResourceManager.GetString("lblAddTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application User.
        /// </summary>
        public static string lblApplicationUser {
            get {
                return ResourceManager.GetString("lblApplicationUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned.
        /// </summary>
        public static string lblAssigned {
            get {
                return ResourceManager.GetString("lblAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned To.
        /// </summary>
        public static string lblAssignedTo {
            get {
                return ResourceManager.GetString("lblAssignedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string lblBacktoList {
            get {
                return ResourceManager.GetString("lblBacktoList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to changed from.
        /// </summary>
        public static string lblchangedfrom {
            get {
                return ResourceManager.GetString("lblchangedfrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Information.
        /// </summary>
        public static string lblClientInformation {
            get {
                return ResourceManager.GetString("lblClientInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string lblClose {
            get {
                return ResourceManager.GetString("lblClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Number.
        /// </summary>
        public static string lblContactNumber {
            get {
                return ResourceManager.GetString("lblContactNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string lblCreate {
            get {
                return ResourceManager.GetString("lblCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Date.
        /// </summary>
        public static string lblCreateDate {
            get {
                return ResourceManager.GetString("lblCreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string lblDescription {
            get {
                return ResourceManager.GetString("lblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter By.
        /// </summary>
        public static string lblEnterBy {
            get {
                return ResourceManager.GetString("lblEnterBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered By.
        /// </summary>
        public static string lblEnteredBy {
            get {
                return ResourceManager.GetString("lblEnteredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string lblFile {
            get {
                return ResourceManager.GetString("lblFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string lblId {
            get {
                return ResourceManager.GetString("lblId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records found.
        /// </summary>
        public static string lblNorecordsfound {
            get {
                return ResourceManager.GetString("lblNorecordsfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string lblNote {
            get {
                return ResourceManager.GetString("lblNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Size.
        /// </summary>
        public static string lblPageSize {
            get {
                return ResourceManager.GetString("lblPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string lblPriority {
            get {
                return ResourceManager.GetString("lblPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while processing....
        /// </summary>
        public static string lblProcessing {
            get {
                return ResourceManager.GetString("lblProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution Description.
        /// </summary>
        public static string lblResolutionDescription {
            get {
                return ResourceManager.GetString("lblResolutionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string lblStatus {
            get {
                return ResourceManager.GetString("lblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Source.
        /// </summary>
        public static string lblTicketSource {
            get {
                return ResourceManager.GetString("lblTicketSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Type.
        /// </summary>
        public static string lblTicketType {
            get {
                return ResourceManager.GetString("lblTicketType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string lblTitle {
            get {
                return ResourceManager.GetString("lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string lblto {
            get {
                return ResourceManager.GetString("lblto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string lblUpdate {
            get {
                return ResourceManager.GetString("lblUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to Close this ticket ?.
        /// </summary>
        public static string msgCloseTicket {
            get {
                return ResourceManager.GetString("msgCloseTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your feedback has been successfully sent and received by our team. We greatly value your input, and we appreciate you taking the time to share with us!.
        /// </summary>
        public static string msgFeedbackMessage {
            get {
                return ResourceManager.GetString("msgFeedbackMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only formats allowed are :jpg, jpeg, png, txt, docx, doc, xlsx, xls, pdf.
        /// </summary>
        public static string msgFormatsAllowed {
            get {
                return ResourceManager.GetString("msgFormatsAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to remove this file ?.
        /// </summary>
        public static string msgRemoveImageFile {
            get {
                return ResourceManager.GetString("msgRemoveImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only formats allowed are :jpg, jpeg, png, txt, docx, doc, xlsx, xls, pdf.
        /// </summary>
        public static string msgTicketAllowFileFormat {
            get {
                return ResourceManager.GetString("msgTicketAllowFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click here for download this file.
        /// </summary>
        public static string titleclickherefordownloadthisfile {
            get {
                return ResourceManager.GetString("titleclickherefordownloadthisfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click here for remove this file.
        /// </summary>
        public static string titleclickhereforremovethisfile {
            get {
                return ResourceManager.GetString("titleclickhereforremovethisfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Desk.
        /// </summary>
        public static string titleTicketDesk {
            get {
                return ResourceManager.GetString("titleTicketDesk", resourceCulture);
            }
        }
    }
}
