//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBISCCMWeb.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BeneficialOwnershipLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BeneficialOwnershipLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SBISCCMWeb.LanguageResources.DandB.BeneficialOwnershipLang", typeof(BeneficialOwnershipLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficial Ownership Data.
        /// </summary>
        public static string hdrBeneficialOwnershipData {
            get {
                return ResourceManager.GetString("hdrBeneficialOwnershipData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficiary Graph View.
        /// </summary>
        public static string hdrBenificiaryGraphView {
            get {
                return ResourceManager.GetString("hdrBenificiaryGraphView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficial Ownerships and Relationships.
        /// </summary>
        public static string hdrOwnershipsRelationships {
            get {
                return ResourceManager.GetString("hdrOwnershipsRelationships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screening Details.
        /// </summary>
        public static string hdrScreeningDetails {
            get {
                return ResourceManager.GetString("hdrScreeningDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert Type.
        /// </summary>
        public static string lblAlertType {
            get {
                return ResourceManager.GetString("lblAlertType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string lblBack {
            get {
                return ResourceManager.GetString("lblBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficial.
        /// </summary>
        public static string lblBenificiary {
            get {
                return ResourceManager.GetString("lblBenificiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string lblCategory {
            get {
                return ResourceManager.GetString("lblCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string lblCountry {
            get {
                return ResourceManager.GetString("lblCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string lblDate {
            get {
                return ResourceManager.GetString("lblDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsBeneficiary.
        /// </summary>
        public static string lblisBenificiary {
            get {
                return ResourceManager.GetString("lblisBenificiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated.
        /// </summary>
        public static string lblLastUpdated {
            get {
                return ResourceManager.GetString("lblLastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string lblList {
            get {
                return ResourceManager.GetString("lblList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string lblNotes {
            get {
                return ResourceManager.GetString("lblNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string lblRefresh {
            get {
                return ResourceManager.GetString("lblRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screened Alert - Code.
        /// </summary>
        public static string lblScreenedAlert_Code {
            get {
                return ResourceManager.GetString("lblScreenedAlert_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screened Date.
        /// </summary>
        public static string lblScreenedDate {
            get {
                return ResourceManager.GetString("lblScreenedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screened Result.
        /// </summary>
        public static string lblScreenedResult {
            get {
                return ResourceManager.GetString("lblScreenedResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screening Result.
        /// </summary>
        public static string lblScreeningResult {
            get {
                return ResourceManager.GetString("lblScreeningResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Ownership.
        /// </summary>
        public static string lblScreenOwnership {
            get {
                return ResourceManager.GetString("lblScreenOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen ownership list.
        /// </summary>
        public static string lblScreenownershiplist {
            get {
                return ResourceManager.GetString("lblScreenownershiplist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string spnAddress {
            get {
                return ResourceManager.GetString("spnAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Ownership Type.
        /// </summary>
        public static string spnControlOwnershipType {
            get {
                return ResourceManager.GetString("spnControlOwnershipType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate Beneficiaries.
        /// </summary>
        public static string spnCorporateBenificiaries {
            get {
                return ResourceManager.GetString("spnCorporateBenificiaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree Of Sepration.
        /// </summary>
        public static string spnDegreeOfSepration {
            get {
                return ResourceManager.GetString("spnDegreeOfSepration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct.
        /// </summary>
        public static string spnDirect {
            get {
                return ResourceManager.GetString("spnDirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DUNS.
        /// </summary>
        public static string spnDUNS {
            get {
                return ResourceManager.GetString("spnDUNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity.
        /// </summary>
        public static string spnEntity {
            get {
                return ResourceManager.GetString("spnEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either Company or DUNS Number is required..
        /// </summary>
        public static string spnErrDUNS {
            get {
                return ResourceManager.GetString("spnErrDUNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Excel.
        /// </summary>
        public static string spnExporttoExcel {
            get {
                return ResourceManager.GetString("spnExporttoExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to PDF.
        /// </summary>
        public static string spnExporttoPDF {
            get {
                return ResourceManager.GetString("spnExporttoPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government Orgs.
        /// </summary>
        public static string spnGovernmentOrgs {
            get {
                return ResourceManager.GetString("spnGovernmentOrgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph View.
        /// </summary>
        public static string spnGraphView {
            get {
                return ResourceManager.GetString("spnGraphView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indirect.
        /// </summary>
        public static string spnIndirect {
            get {
                return ResourceManager.GetString("spnIndirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual.
        /// </summary>
        public static string spnIndividual {
            get {
                return ResourceManager.GetString("spnIndividual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Form.
        /// </summary>
        public static string spnLegalForm {
            get {
                return ResourceManager.GetString("spnLegalForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string spnLevel {
            get {
                return ResourceManager.GetString("spnLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string spnName {
            get {
                return ResourceManager.GetString("spnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating.
        /// </summary>
        public static string spnOperating {
            get {
                return ResourceManager.GetString("spnOperating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string spnOthers {
            get {
                return ResourceManager.GetString("spnOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ownership.
        /// </summary>
        public static string spnOwnership {
            get {
                return ResourceManager.GetString("spnOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ownership Individuals.
        /// </summary>
        public static string spnOwnershipIndividuals {
            get {
                return ResourceManager.GetString("spnOwnershipIndividuals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ownership Organizations.
        /// </summary>
        public static string spnOwnershipOrganizations {
            get {
                return ResourceManager.GetString("spnOwnershipOrganizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ownerships.
        /// </summary>
        public static string spnOwnerships {
            get {
                return ResourceManager.GetString("spnOwnerships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privately Owned.
        /// </summary>
        public static string spnPrivatelyOwned {
            get {
                return ResourceManager.GetString("spnPrivatelyOwned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Orgs.
        /// </summary>
        public static string spnPrivateOrgs {
            get {
                return ResourceManager.GetString("spnPrivateOrgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publicly Owned/Traded Companies.
        /// </summary>
        public static string spnPubliclyOwnedTradedCompanies {
            get {
                return ResourceManager.GetString("spnPubliclyOwnedTradedCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PubliclyTrading Orgs.
        /// </summary>
        public static string spnPubliclyTradingOrgs {
            get {
                return ResourceManager.GetString("spnPubliclyTradingOrgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationships.
        /// </summary>
        public static string spnRelationships {
            get {
                return ResourceManager.GetString("spnRelationships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string spnRole {
            get {
                return ResourceManager.GetString("spnRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in full Screen.
        /// </summary>
        public static string spnShowInFullScreen {
            get {
                return ResourceManager.GetString("spnShowInFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Owned.
        /// </summary>
        public static string spnStateOwned {
            get {
                return ResourceManager.GetString("spnStateOwned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Owned Orgs.
        /// </summary>
        public static string spnStateOwnedOrgs {
            get {
                return ResourceManager.GetString("spnStateOwnedOrgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabular View.
        /// </summary>
        public static string spnTabularView {
            get {
                return ResourceManager.GetString("spnTabularView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Company.
        /// </summary>
        public static string spnTargetCompany {
            get {
                return ResourceManager.GetString("spnTargetCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string spnType {
            get {
                return ResourceManager.GetString("spnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Beneficial OwnershipData.
        /// </summary>
        public static string titleSearchBeneficialOwnershipData {
            get {
                return ResourceManager.GetString("titleSearchBeneficialOwnershipData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Beneficiary Details.
        /// </summary>
        public static string titleViewBenificiaryDetails {
            get {
                return ResourceManager.GetString("titleViewBenificiaryDetails", resourceCulture);
            }
        }
    }
}
