//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBISCCMWeb.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CleanDataLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CleanDataLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SBISCCMWeb.LanguageResources.DandB.CleanDataLang", typeof(CleanDataLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Company.
        /// </summary>
        public static string btnAddCompany {
            get {
                return ResourceManager.GetString("btnAddCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new company.
        /// </summary>
        public static string hdrAddnewcompany {
            get {
                return ResourceManager.GetString("hdrAddnewcompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean Data.
        /// </summary>
        public static string hdrCleanData {
            get {
                return ResourceManager.GetString("hdrCleanData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Filter.
        /// </summary>
        public static string hdrCompanyFilter {
            get {
                return ResourceManager.GetString("hdrCompanyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Match Records.
        /// </summary>
        public static string hdrReMatchRecords {
            get {
                return ResourceManager.GetString("hdrReMatchRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Data.
        /// </summary>
        public static string hdrSearchData {
            get {
                return ResourceManager.GetString("hdrSearchData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string lblActive {
            get {
                return ResourceManager.GetString("lblActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Company.
        /// </summary>
        public static string lblAddCompany {
            get {
                return ResourceManager.GetString("lblAddCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Actions.
        /// </summary>
        public static string lblAdditionalActions {
            get {
                return ResourceManager.GetString("lblAdditionalActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Fields.
        /// </summary>
        public static string lblAdditionalFields {
            get {
                return ResourceManager.GetString("lblAdditionalFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string lblAddress {
            get {
                return ResourceManager.GetString("lblAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address1.
        /// </summary>
        public static string lblAddress1 {
            get {
                return ResourceManager.GetString("lblAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address2.
        /// </summary>
        public static string lblAddress2 {
            get {
                return ResourceManager.GetString("lblAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt. Address.
        /// </summary>
        public static string lblAltAddress {
            get {
                return ResourceManager.GetString("lblAltAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt. Address2.
        /// </summary>
        public static string lblAltAddress2 {
            get {
                return ResourceManager.GetString("lblAltAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt City.
        /// </summary>
        public static string lblAltCity {
            get {
                return ResourceManager.GetString("lblAltCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt. Company Name.
        /// </summary>
        public static string lblAltCompanyName {
            get {
                return ResourceManager.GetString("lblAltCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt Country.
        /// </summary>
        public static string lblAltCountry {
            get {
                return ResourceManager.GetString("lblAltCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt. PostalCode.
        /// </summary>
        public static string lblAltPostalCode {
            get {
                return ResourceManager.GetString("lblAltPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt. State.
        /// </summary>
        public static string lblAltState {
            get {
                return ResourceManager.GetString("lblAltState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign DUNS.
        /// </summary>
        public static string lblAssignDUNS {
            get {
                return ResourceManager.GetString("lblAssignDUNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bing Search.
        /// </summary>
        public static string lblBingSearch {
            get {
                return ResourceManager.GetString("lblBingSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bing search.
        /// </summary>
        public static string lblBingsearches {
            get {
                return ResourceManager.GetString("lblBingsearches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC.
        /// </summary>
        public static string lblCC {
            get {
                return ResourceManager.GetString("lblCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEO Name.
        /// </summary>
        public static string lblCEOName {
            get {
                return ResourceManager.GetString("lblCEOName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string lblCity {
            get {
                return ResourceManager.GetString("lblCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Exact Match.
        /// </summary>
        public static string lblCityExactMatch {
            get {
                return ResourceManager.GetString("lblCityExactMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string lblCompany {
            get {
                return ResourceManager.GetString("lblCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company/National Id/URL/Email/DUNS.
        /// </summary>
        public static string lblCompanyHeader {
            get {
                return ResourceManager.GetString("lblCompanyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string lblCopy {
            get {
                return ResourceManager.GetString("lblCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string lblCountry {
            get {
                return ResourceManager.GetString("lblCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Group.
        /// </summary>
        public static string lblCountryGroup {
            get {
                return ResourceManager.GetString("lblCountryGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DUNS NO.
        /// </summary>
        public static string lblDUNSNO {
            get {
                return ResourceManager.GetString("lblDUNSNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Code.
        /// </summary>
        public static string lblErrorCode {
            get {
                return ResourceManager.GetString("lblErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Description.
        /// </summary>
        public static string lblErrorDescription {
            get {
                return ResourceManager.GetString("lblErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude Non HeadQuarters.
        /// </summary>
        public static string lblExcludeNonHeadQuarters {
            get {
                return ResourceManager.GetString("lblExcludeNonHeadQuarters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude Non Marketable.
        /// </summary>
        public static string lblExcludeNonMarketable {
            get {
                return ResourceManager.GetString("lblExcludeNonMarketable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude Out of Business.
        /// </summary>
        public static string lblExcludeOutofBusiness {
            get {
                return ResourceManager.GetString("lblExcludeOutofBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude Undeliverable.
        /// </summary>
        public static string lblExcludeUndeliverable {
            get {
                return ResourceManager.GetString("lblExcludeUndeliverable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude Unreachable.
        /// </summary>
        public static string lblExcludeUnreachable {
            get {
                return ResourceManager.GetString("lblExcludeUnreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Search.
        /// </summary>
        public static string lblGoogleSearch {
            get {
                return ResourceManager.GetString("lblGoogleSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Process.
        /// </summary>
        public static string lblImportProcess {
            get {
                return ResourceManager.GetString("lblImportProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inp DUNS NO.
        /// </summary>
        public static string lblInpDUNSNO {
            get {
                return ResourceManager.GetString("lblInpDUNSNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investigate.
        /// </summary>
        public static string lblInvestigate {
            get {
                return ResourceManager.GetString("lblInvestigate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investigate Selected Records.
        /// </summary>
        public static string lblInvestigateSelectedRecords {
            get {
                return ResourceManager.GetString("lblInvestigateSelectedRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string lblLanguage {
            get {
                return ResourceManager.GetString("lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing Address.
        /// </summary>
        public static string lblMailingAddress {
            get {
                return ResourceManager.GetString("lblMailingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketable.
        /// </summary>
        public static string lblMarketable {
            get {
                return ResourceManager.GetString("lblMarketable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Grade.
        /// </summary>
        public static string lblMatchGrade {
            get {
                return ResourceManager.GetString("lblMatchGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MDP.
        /// </summary>
        public static string lblMDP {
            get {
                return ResourceManager.GetString("lblMDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data are available..
        /// </summary>
        public static string lblNoDataAreAvailable {
            get {
                return ResourceManager.GetString("lblNoDataAreAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available..
        /// </summary>
        public static string lblNodataavailable {
            get {
                return ResourceManager.GetString("lblNodataavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Marketable.
        /// </summary>
        public static string lblNonMarketable {
            get {
                return ResourceManager.GetString("lblNonMarketable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating.
        /// </summary>
        public static string lblOperating {
            get {
                return ResourceManager.GetString("lblOperating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of business.
        /// </summary>
        public static string lblOutofbusiness {
            get {
                return ResourceManager.GetString("lblOutofbusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Size.
        /// </summary>
        public static string lblPageSize {
            get {
                return ResourceManager.GetString("lblPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string lblPhone {
            get {
                return ResourceManager.GetString("lblPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select all tags..
        /// </summary>
        public static string lblPleaseselectalltags {
            get {
                return ResourceManager.GetString("lblPleaseselectalltags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Country.
        /// </summary>
        public static string lblPleaseSelectCountry {
            get {
                return ResourceManager.GetString("lblPleaseSelectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Language.
        /// </summary>
        public static string lblPleaseSelectLanguage {
            get {
                return ResourceManager.GetString("lblPleaseSelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal.
        /// </summary>
        public static string lblPostal {
            get {
                return ResourceManager.GetString("lblPostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purge.
        /// </summary>
        public static string lblPurge {
            get {
                return ResourceManager.GetString("lblPurge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purge From File.
        /// </summary>
        public static string lblPurgeFromFile {
            get {
                return ResourceManager.GetString("lblPurgeFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purge Record.
        /// </summary>
        public static string lblPurgeRecord {
            get {
                return ResourceManager.GetString("lblPurgeRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purge Records.
        /// </summary>
        public static string lblPurgeRecords {
            get {
                return ResourceManager.GetString("lblPurgeRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purge Selected Records.
        /// </summary>
        public static string lblPurgeSelectedRecords {
            get {
                return ResourceManager.GetString("lblPurgeSelectedRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Number.
        /// </summary>
        public static string lblRegistrationNumber {
            get {
                return ResourceManager.GetString("lblRegistrationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Type.
        /// </summary>
        public static string lblRegistrationType {
            get {
                return ResourceManager.GetString("lblRegistrationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Match.
        /// </summary>
        public static string lblRematch {
            get {
                return ResourceManager.GetString("lblRematch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Match Records.
        /// </summary>
        public static string lblReMatchRecords {
            get {
                return ResourceManager.GetString("lblReMatchRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Match Selected Records.
        /// </summary>
        public static string lblReMatchSelectedRecords {
            get {
                return ResourceManager.GetString("lblReMatchSelectedRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Country.
        /// </summary>
        public static string lblRequiredCountry {
            get {
                return ResourceManager.GetString("lblRequiredCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill SrcRecordId.
        /// </summary>
        public static string lblRequiredSrcRecordId {
            get {
                return ResourceManager.GetString("lblRequiredSrcRecordId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string lblSearch {
            get {
                return ResourceManager.GetString("lblSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By Address.
        /// </summary>
        public static string lblSearchByAddress {
            get {
                return ResourceManager.GetString("lblSearchByAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By Alt. Fields.
        /// </summary>
        public static string lblSearchByAltFields {
            get {
                return ResourceManager.GetString("lblSearchByAltFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By Company.
        /// </summary>
        public static string lblSearchByCompany {
            get {
                return ResourceManager.GetString("lblSearchByCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string lblSelectAll {
            get {
                return ResourceManager.GetString("lblSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Src Id.
        /// </summary>
        public static string lblSrcId {
            get {
                return ResourceManager.GetString("lblSrcId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SrcRec ID.
        /// </summary>
        public static string lblSrcRecID {
            get {
                return ResourceManager.GetString("lblSrcRecID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SrcRecordId.
        /// </summary>
        public static string lblSrcRecordId {
            get {
                return ResourceManager.GetString("lblSrcRecordId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string lblState {
            get {
                return ResourceManager.GetString("lblState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Exact Match.
        /// </summary>
        public static string lblStateExactMatch {
            get {
                return ResourceManager.GetString("lblStateExactMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street#.
        /// </summary>
        public static string lblStreet {
            get {
                return ResourceManager.GetString("lblStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Name.
        /// </summary>
        public static string lblStreetName {
            get {
                return ResourceManager.GetString("lblStreetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string lblTag {
            get {
                return ResourceManager.GetString("lblTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag is required..
        /// </summary>
        public static string lblTagisrequired {
            get {
                return ResourceManager.GetString("lblTagisrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string lblTags {
            get {
                return ResourceManager.GetString("lblTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Record.
        /// </summary>
        public static string lblUpdateRecord {
            get {
                return ResourceManager.GetString("lblUpdateRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate Input Address.
        /// </summary>
        public static string lblValidateInputAddress {
            get {
                return ResourceManager.GetString("lblValidateInputAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Candidates on Map.
        /// </summary>
        public static string lblViewCandidatesonMap {
            get {
                return ResourceManager.GetString("lblViewCandidatesonMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string lblWebsite {
            get {
                return ResourceManager.GetString("lblWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip.
        /// </summary>
        public static string lblZip {
            get {
                return ResourceManager.GetString("lblZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New company added successfully.
        /// </summary>
        public static string msgAddNewCompany {
            get {
                return ResourceManager.GetString("msgAddNewCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to assign this DUNS Number to this Input record?.
        /// </summary>
        public static string msgAssignDUNS {
            get {
                return ResourceManager.GetString("msgAssignDUNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure, you want to purge this record ?.
        /// </summary>
        public static string msgCleanSearchPurgeRecord {
            get {
                return ResourceManager.GetString("msgCleanSearchPurgeRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data rejected successfully.
        /// </summary>
        public static string msgDataRejected {
            get {
                return ResourceManager.GetString("msgDataRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by Error Code.
        /// </summary>
        public static string msgFilterByErrorCode {
            get {
                return ResourceManager.GetString("msgFilterByErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only formats allowed are :.
        /// </summary>
        public static string msgFormatsAllowed {
            get {
                return ResourceManager.GetString("msgFormatsAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No record(s) found.
        /// </summary>
        public static string msgNoRecords {
            get {
                return ResourceManager.GetString("msgNoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total 0 records are affected, are you sure you want to continue ?.
        /// </summary>
        public static string msgNoRecordsAffected {
            get {
                return ResourceManager.GetString("msgNoRecordsAffected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only numeric values accepted..
        /// </summary>
        public static string msgOnlyNumbersAllowed {
            get {
                return ResourceManager.GetString("msgOnlyNumbersAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to Purge this record ?.
        /// </summary>
        public static string msgPurgeRecord {
            get {
                return ResourceManager.GetString("msgPurgeRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to purge records ?.
        /// </summary>
        public static string msgPurgeRecords {
            get {
                return ResourceManager.GetString("msgPurgeRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to re-match this record ?.
        /// </summary>
        public static string msgRematchRecord {
            get {
                return ResourceManager.GetString("msgRematchRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to records are affected, are you sure you want to continue ?.
        /// </summary>
        public static string msgRematchRecords {
            get {
                return ResourceManager.GetString("msgRematchRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data ReMatch Request Completed Successfully..
        /// </summary>
        public static string msgReMatchRequestCompleted {
            get {
                return ResourceManager.GetString("msgReMatchRequestCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rows sent for ReMatch..
        /// </summary>
        public static string msgRowsSentForReMatch {
            get {
                return ResourceManager.GetString("msgRowsSentForReMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one record to purge.
        /// </summary>
        public static string msgSelectRecordToPurge {
            get {
                return ResourceManager.GetString("msgSelectRecordToPurge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one record to re-match.
        /// </summary>
        public static string msgSelectRecordToRematch {
            get {
                return ResourceManager.GetString("msgSelectRecordToRematch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one record to investigate.
        /// </summary>
        public static string msgSelectRecotdToInvestigate {
            get {
                return ResourceManager.GetString("msgSelectRecotdToInvestigate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string msgTotal {
            get {
                return ResourceManager.GetString("msgTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings updated successfully..
        /// </summary>
        public static string msgUpdateSettings {
            get {
                return ResourceManager.GetString("msgUpdateSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean Data.
        /// </summary>
        public static string titleCleanData {
            get {
                return ResourceManager.GetString("titleCleanData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleanse Match.
        /// </summary>
        public static string titleCleanseMatch {
            get {
                return ResourceManager.GetString("titleCleanseMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Company Filter.
        /// </summary>
        public static string titleClearCompanyFilter {
            get {
                return ResourceManager.GetString("titleClearCompanyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrichment detail.
        /// </summary>
        public static string titleEnrichmentdetail {
            get {
                return ResourceManager.GetString("titleEnrichmentdetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Match Records.
        /// </summary>
        public static string titleReMatchRecords {
            get {
                return ResourceManager.GetString("titleReMatchRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Data.
        /// </summary>
        public static string titleSearchData {
            get {
                return ResourceManager.GetString("titleSearchData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Default Page Size.
        /// </summary>
        public static string titleSetDefaultPageSize {
            get {
                return ResourceManager.GetString("titleSetDefaultPageSize", resourceCulture);
            }
        }
    }
}
