//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBISCCMWeb.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExportLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExportLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SBISCCMWeb.LanguageResources.DandB.ExportLang", typeof(ExportLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Data Queue.
        /// </summary>
        public static string lblActiveDataQueue {
            get {
                return ResourceManager.GetString("lblActiveDataQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api Layer.
        /// </summary>
        public static string lblApiLayer {
            get {
                return ResourceManager.GetString("lblApiLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both.
        /// </summary>
        public static string lblBoth {
            get {
                return ResourceManager.GetString("lblBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string lblCancel {
            get {
                return ResourceManager.GetString("lblCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string lblCancelled {
            get {
                return ResourceManager.GetString("lblCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Data.
        /// </summary>
        public static string lblCompanyData {
            get {
                return ResourceManager.GetString("lblCompanyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Group.
        /// </summary>
        public static string lblCountryGroup {
            get {
                return ResourceManager.GetString("lblCountryGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV.
        /// </summary>
        public static string lblCSV {
            get {
                return ResourceManager.GetString("lblCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Delimiter.
        /// </summary>
        public static string lblCustomDelimiter {
            get {
                return ResourceManager.GetString("lblCustomDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string lblDelete {
            get {
                return ResourceManager.GetString("lblDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delimiter.
        /// </summary>
        public static string lblDelimiter {
            get {
                return ResourceManager.GetString("lblDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string lblDownload {
            get {
                return ResourceManager.GetString("lblDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrichment.
        /// </summary>
        public static string lblEnrichment {
            get {
                return ResourceManager.GetString("lblEnrichment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrichment Output.
        /// </summary>
        public static string lblEnrichmentOutput {
            get {
                return ResourceManager.GetString("lblEnrichmentOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel.
        /// </summary>
        public static string lblExcel {
            get {
                return ResourceManager.GetString("lblExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Options.
        /// </summary>
        public static string lblExportOptions {
            get {
                return ResourceManager.GetString("lblExportOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Status.
        /// </summary>
        public static string lblExportStatus {
            get {
                return ResourceManager.GetString("lblExportStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string lblFailed {
            get {
                return ResourceManager.GetString("lblFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string lblFileName {
            get {
                return ResourceManager.GetString("lblFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter file name..
        /// </summary>
        public static string lblFileNameRequire {
            get {
                return ResourceManager.GetString("lblFileNameRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string lblFormat {
            get {
                return ResourceManager.GetString("lblFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select format..
        /// </summary>
        public static string lblFormatRequire {
            get {
                return ResourceManager.GetString("lblFormatRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Process.
        /// </summary>
        public static string lblImportProcess {
            get {
                return ResourceManager.GetString("lblImportProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Export Date and Time.
        /// </summary>
        public static string lblIncludeExportDateAndTime {
            get {
                return ResourceManager.GetString("lblIncludeExportDateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Header.
        /// </summary>
        public static string lblIncludeHeader {
            get {
                return ResourceManager.GetString("lblIncludeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include SrcRecordID.
        /// </summary>
        public static string lblIncludeSrcRecordID {
            get {
                return ResourceManager.GetString("lblIncludeSrcRecordID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Subdomain.
        /// </summary>
        public static string lblIncludeSubdomain {
            get {
                return ResourceManager.GetString("lblIncludeSubdomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Process.
        /// </summary>
        public static string lblInProcess {
            get {
                return ResourceManager.GetString("lblInProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Delimiter.
        /// </summary>
        public static string lblInsertDelimiter {
            get {
                return ResourceManager.GetString("lblInsertDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Exact Match.
        /// </summary>
        public static string lblIsExactMatch {
            get {
                return ResourceManager.GetString("lblIsExactMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOB Tags.
        /// </summary>
        public static string lblLOBTags {
            get {
                return ResourceManager.GetString("lblLOBTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Confidence Queue.
        /// </summary>
        public static string lblLowConfidenceQueue {
            get {
                return ResourceManager.GetString("lblLowConfidenceQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark As Exported.
        /// </summary>
        public static string lblMarkAsExported {
            get {
                return ResourceManager.GetString("lblMarkAsExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Output.
        /// </summary>
        public static string lblMatchOutput {
            get {
                return ResourceManager.GetString("lblMatchOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring Notification.
        /// </summary>
        public static string lblMonitoringNotification {
            get {
                return ResourceManager.GetString("lblMonitoringNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring Notification Data Status.
        /// </summary>
        public static string lblMonitoringNotificationDataStatus {
            get {
                return ResourceManager.GetString("lblMonitoringNotificationDataStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring Notifications.
        /// </summary>
        public static string lblMonitoringNotifications {
            get {
                return ResourceManager.GetString("lblMonitoringNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Match Queue.
        /// </summary>
        public static string lblNoMatchQueue {
            get {
                return ResourceManager.GetString("lblNoMatchQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Record(s) found.
        /// </summary>
        public static string lblNoRecordfound {
            get {
                return ResourceManager.GetString("lblNoRecordfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Tag.
        /// </summary>
        public static string lblNoTag {
            get {
                return ResourceManager.GetString("lblNoTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: Mark as Exported does not apply to Low Confidence Queue and No Match Queue outputs.
        /// </summary>
        public static string lblNoteMarkAsExported {
            get {
                return ResourceManager.GetString("lblNoteMarkAsExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file Name.
        /// </summary>
        public static string lblOutputfileName {
            get {
                return ResourceManager.GetString("lblOutputfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Queue.
        /// </summary>
        public static string lblOutputQueue {
            get {
                return ResourceManager.GetString("lblOutputQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select atleast one output type.
        /// </summary>
        public static string lblOutputTypeRequire {
            get {
                return ResourceManager.GetString("lblOutputTypeRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Size.
        /// </summary>
        public static string lblPageSize {
            get {
                return ResourceManager.GetString("lblPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while processing....
        /// </summary>
        public static string lblProcessing {
            get {
                return ResourceManager.GetString("lblProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualifier All Columns.
        /// </summary>
        public static string lblQualifierAllColumns {
            get {
                return ResourceManager.GetString("lblQualifierAllColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string lblReady {
            get {
                return ResourceManager.GetString("lblReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Export Data.
        /// </summary>
        public static string lblReExportData {
            get {
                return ResourceManager.GetString("lblReExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested Date.
        /// </summary>
        public static string lblRequestedDate {
            get {
                return ResourceManager.GetString("lblRequestedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill Delimiter.
        /// </summary>
        public static string lblRequiredDelimiter {
            get {
                return ResourceManager.GetString("lblRequiredDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string lblSave {
            get {
                return ResourceManager.GetString("lblSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SrcRecID.
        /// </summary>
        public static string lblSrcRecID {
            get {
                return ResourceManager.GetString("lblSrcRecID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SrcRecordId.
        /// </summary>
        public static string lblSrcRecordId {
            get {
                return ResourceManager.GetString("lblSrcRecordId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SrcRecordIdList.
        /// </summary>
        public static string lblSrcRecordIdList {
            get {
                return ResourceManager.GetString("lblSrcRecordIdList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string lblStatus {
            get {
                return ResourceManager.GetString("lblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1 - Select Filters (Optional).
        /// </summary>
        public static string lblStep1SelectFilters {
            get {
                return ResourceManager.GetString("lblStep1SelectFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2 - Select Output.
        /// </summary>
        public static string lblStep2SelectOutput {
            get {
                return ResourceManager.GetString("lblStep2SelectOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 3 - Finalize Export.
        /// </summary>
        public static string lblStep3FinalizeExport {
            get {
                return ResourceManager.GetString("lblStep3FinalizeExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 3 - Select Output Format.
        /// </summary>
        public static string lblStep3SelectOutput {
            get {
                return ResourceManager.GetString("lblStep3SelectOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 4 - Finalize Export (Optional).
        /// </summary>
        public static string lblStep4FinalizeExport {
            get {
                return ResourceManager.GetString("lblStep4FinalizeExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string lblSubmit {
            get {
                return ResourceManager.GetString("lblSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab Separated.
        /// </summary>
        public static string lblTabSeparated {
            get {
                return ResourceManager.GetString("lblTabSeparated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string lblTags {
            get {
                return ResourceManager.GetString("lblTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferred Duns.
        /// </summary>
        public static string lblTransferredDuns {
            get {
                return ResourceManager.GetString("lblTransferredDuns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un-flag Exported Data.
        /// </summary>
        public static string lblUnflagExportedData {
            get {
                return ResourceManager.GetString("lblUnflagExportedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid file name..
        /// </summary>
        public static string lblValidFileName {
            get {
                return ResourceManager.GetString("lblValidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Zip.
        /// </summary>
        public static string lblZip {
            get {
                return ResourceManager.GetString("lblZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api Layer.
        /// </summary>
        public static string msgApiLayer {
            get {
                return ResourceManager.GetString("msgApiLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure, you want to cancel this export data request ?.
        /// </summary>
        public static string msgCancelExportDataRequest {
            get {
                return ResourceManager.GetString("msgCancelExportDataRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data rejected successfully.
        /// </summary>
        public static string msgDataRejected {
            get {
                return ResourceManager.GetString("msgDataRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data are Un-Flagged and you can export using Export options..
        /// </summary>
        public static string msgDataUnflagged {
            get {
                return ResourceManager.GetString("msgDataUnflagged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete record ?.
        /// </summary>
        public static string msgDeleteRecord {
            get {
                return ResourceManager.GetString("msgDeleteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delimiter Value.
        /// </summary>
        public static string msgDelimiterValue {
            get {
                return ResourceManager.GetString("msgDelimiterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your data request has been submitted successfully, we will notify you once your file is ready to download..
        /// </summary>
        public static string msgExportDataSave {
            get {
                return ResourceManager.GetString("msgExportDataSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileName is already exists, please enter different filename..
        /// </summary>
        public static string msgFileExists {
            get {
                return ResourceManager.GetString("msgFileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileName is already exists, please enter different filename..
        /// </summary>
        public static string msgFileNameExists {
            get {
                return ResourceManager.GetString("msgFileNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Process.
        /// </summary>
        public static string msgImportProcess {
            get {
                return ResourceManager.GetString("msgImportProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Exact Match.
        /// </summary>
        public static string msgIsExactMatch {
            get {
                return ResourceManager.GetString("msgIsExactMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export data request cancelled successfully.
        /// </summary>
        public static string msgJobCancel {
            get {
                return ResourceManager.GetString("msgJobCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your export data request is already in process, we can&apos;t cancel it.
        /// </summary>
        public static string msgJobInProcess {
            get {
                return ResourceManager.GetString("msgJobInProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOB Tag.
        /// </summary>
        public static string msgLOBTag {
            get {
                return ResourceManager.GetString("msgLOBTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark As Exported.
        /// </summary>
        public static string msgMarkAsExported {
            get {
                return ResourceManager.GetString("msgMarkAsExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to mark data as exported?.
        /// </summary>
        public static string msgMarkDataAsExported {
            get {
                return ResourceManager.GetString("msgMarkDataAsExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data not found..
        /// </summary>
        public static string msgNoDataFound {
            get {
                return ResourceManager.GetString("msgNoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note : There is no filter selected , you will be downloading all your data contained within matchbook.
        /// </summary>
        public static string msgNoFilterSelected {
            get {
                return ResourceManager.GetString("msgNoFilterSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data not found..
        /// </summary>
        public static string msgNoRecordFound {
            get {
                return ResourceManager.GetString("msgNoRecordFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total 0 records are affected, are you sure you want to continue ?.
        /// </summary>
        public static string msgNoRecordsAffected {
            get {
                return ResourceManager.GetString("msgNoRecordsAffected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No record(s) found.
        /// </summary>
        public static string msgNoRecordsFound {
            get {
                return ResourceManager.GetString("msgNoRecordsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Format.
        /// </summary>
        public static string msgOutputFormat {
            get {
                return ResourceManager.GetString("msgOutputFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Output.
        /// </summary>
        public static string msgSelectedOutput {
            get {
                return ResourceManager.GetString("msgSelectedOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Src Record Id.
        /// </summary>
        public static string msgSrcRecordId {
            get {
                return ResourceManager.GetString("msgSrcRecordId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string msgTag {
            get {
                return ResourceManager.GetString("msgTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data are Un-Flagged and you can export using Export options..
        /// </summary>
        public static string msgUnFlagData {
            get {
                return ResourceManager.GetString("msgUnFlagData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV.
        /// </summary>
        public static string titleCSV {
            get {
                return ResourceManager.GetString("titleCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Delimiter.
        /// </summary>
        public static string titleCustomDelimiter {
            get {
                return ResourceManager.GetString("titleCustomDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Match.
        /// </summary>
        public static string titleDataMatch {
            get {
                return ResourceManager.GetString("titleDataMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string titleDownload {
            get {
                return ResourceManager.GetString("titleDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel.
        /// </summary>
        public static string titleExcel {
            get {
                return ResourceManager.GetString("titleExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Data.
        /// </summary>
        public static string titleExportData {
            get {
                return ResourceManager.GetString("titleExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab Separated.
        /// </summary>
        public static string titleTabSeparated {
            get {
                return ResourceManager.GetString("titleTabSeparated", resourceCulture);
            }
        }
    }
}
