//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBISCCMWeb.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FamilyTreeLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FamilyTreeLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SBISCCMWeb.LanguageResources.DandB.FamilyTreeLang", typeof(FamilyTreeLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Node.
        /// </summary>
        public static string hdrAddNode {
            get {
                return ResourceManager.GetString("hdrAddNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate Hierarchy Management Solution.
        /// </summary>
        public static string hdrCorporateHierarchyManagementSolution {
            get {
                return ResourceManager.GetString("hdrCorporateHierarchyManagementSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Family Tree.
        /// </summary>
        public static string hdrCreateFamilyTree {
            get {
                return ResourceManager.GetString("hdrCreateFamilyTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Family Tree.
        /// </summary>
        public static string hdrDuplicateFamilyTree {
            get {
                return ResourceManager.GetString("hdrDuplicateFamilyTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Tree.
        /// </summary>
        public static string hdrFamilyTree {
            get {
                return ResourceManager.GetString("hdrFamilyTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Tree Detail.
        /// </summary>
        public static string hdrFamilyTreeDetail {
            get {
                return ResourceManager.GetString("hdrFamilyTreeDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Populate a new Family Tree from Corporate Linkage.
        /// </summary>
        public static string hdrPopulateanewFamilyTreefromCorporateLinkage {
            get {
                return ResourceManager.GetString("hdrPopulateanewFamilyTreefromCorporateLinkage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string lblAdd {
            get {
                return ResourceManager.GetString("lblAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Action.
        /// </summary>
        public static string lblAdditionalAction {
            get {
                return ResourceManager.GetString("lblAdditionalAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Actions.
        /// </summary>
        public static string lblAdditionalActions {
            get {
                return ResourceManager.GetString("lblAdditionalActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Node.
        /// </summary>
        public static string lblAddNode {
            get {
                return ResourceManager.GetString("lblAddNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string lblAddress {
            get {
                return ResourceManager.GetString("lblAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate Id.
        /// </summary>
        public static string lblAlternateId {
            get {
                return ResourceManager.GetString("lblAlternateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Family Tree.
        /// </summary>
        public static string lblCreateNewFamilyTree {
            get {
                return ResourceManager.GetString("lblCreateNewFamilyTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Family Tree.
        /// </summary>
        public static string lblDeleteFamilyTree {
            get {
                return ResourceManager.GetString("lblDeleteFamilyTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail Id.
        /// </summary>
        public static string lblDetailId {
            get {
                return ResourceManager.GetString("lblDetailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duns Number.
        /// </summary>
        public static string lblDunsNumber {
            get {
                return ResourceManager.GetString("lblDunsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Family Tree.
        /// </summary>
        public static string lblDuplicateFamilyTree {
            get {
                return ResourceManager.GetString("lblDuplicateFamilyTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editable.
        /// </summary>
        public static string lblEditable {
            get {
                return ResourceManager.GetString("lblEditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Alternate Id.
        /// </summary>
        public static string lblEnterAlternateId {
            get {
                return ResourceManager.GetString("lblEnterAlternateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Family Tree Name.
        /// </summary>
        public static string lblEnterFamilyTreeName {
            get {
                return ResourceManager.GetString("lblEnterFamilyTreeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Family Tree Type.
        /// </summary>
        public static string lblEnterFamilyTreeType {
            get {
                return ResourceManager.GetString("lblEnterFamilyTreeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FamilyTree.
        /// </summary>
        public static string lblFamilyTree {
            get {
                return ResourceManager.GetString("lblFamilyTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Tree Name.
        /// </summary>
        public static string lblFamilyTreeName {
            get {
                return ResourceManager.GetString("lblFamilyTreeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Tree Type.
        /// </summary>
        public static string lblFamilyTreeType {
            get {
                return ResourceManager.GetString("lblFamilyTreeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modiified By.
        /// </summary>
        public static string lblLastModiifiedBy {
            get {
                return ResourceManager.GetString("lblLastModiifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Refreshed Date.
        /// </summary>
        public static string lblLastRefreshedDate {
            get {
                return ResourceManager.GetString("lblLastRefreshedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked for Edit.
        /// </summary>
        public static string lblLockedforEdit {
            get {
                return ResourceManager.GetString("lblLockedforEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data are available.
        /// </summary>
        public static string lblNodataareavailable {
            get {
                return ResourceManager.GetString("lblNodataareavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node Display Details.
        /// </summary>
        public static string lblNodeDisplayDetails {
            get {
                return ResourceManager.GetString("lblNodeDisplayDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node Type.
        /// </summary>
        public static string lblNodeType {
            get {
                return ResourceManager.GetString("lblNodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Populate a new Family Tree from Corporate Linkage.
        /// </summary>
        public static string lblPopulateanewFamilyTreefromCorporateLinkage {
            get {
                return ResourceManager.GetString("lblPopulateanewFamilyTreefromCorporateLinkage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select--.
        /// </summary>
        public static string lblSelect {
            get {
                return ResourceManager.GetString("lblSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string lblSelected {
            get {
                return ResourceManager.GetString("lblSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side By  Side.
        /// </summary>
        public static string lblSideBySide {
            get {
                return ResourceManager.GetString("lblSideBySide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Panel.
        /// </summary>
        public static string lblSinglePanel {
            get {
                return ResourceManager.GetString("lblSinglePanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string lblType {
            get {
                return ResourceManager.GetString("lblType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Node.
        /// </summary>
        public static string msgAddNode {
            get {
                return ResourceManager.GetString("msgAddNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to add this tree ?.
        /// </summary>
        public static string msgAddTree {
            get {
                return ResourceManager.GetString("msgAddTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to Copy this node ?.
        /// </summary>
        public static string msgCopyNode {
            get {
                return ResourceManager.GetString("msgCopyNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this tree ?.
        /// </summary>
        public static string msgDeleteFamilyTree {
            get {
                return ResourceManager.GetString("msgDeleteFamilyTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this node ?.
        /// </summary>
        public static string msgDeleteNode {
            get {
                return ResourceManager.GetString("msgDeleteNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Node.
        /// </summary>
        public static string msgDeleteNodeSingle {
            get {
                return ResourceManager.GetString("msgDeleteNodeSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Family Tree Created Successfully.
        /// </summary>
        public static string msgDuplicateFamilyTreeCreated {
            get {
                return ResourceManager.GetString("msgDuplicateFamilyTreeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Tree Created Successfully.
        /// </summary>
        public static string msgFamilyTreeCreated {
            get {
                return ResourceManager.GetString("msgFamilyTreeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Tree Node Created Successfully.
        /// </summary>
        public static string msgFamilyTreeNodeCreated {
            get {
                return ResourceManager.GetString("msgFamilyTreeNodeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Tree Node Deleted Successfully.
        /// </summary>
        public static string msgFamilyTreeNodeDeleted {
            get {
                return ResourceManager.GetString("msgFamilyTreeNodeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to move this node ?.
        /// </summary>
        public static string msgMoveNode {
            get {
                return ResourceManager.GetString("msgMoveNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Family Tree.
        /// </summary>
        public static string msgSelectTree {
            get {
                return ResourceManager.GetString("msgSelectTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Tree Type.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand this branch.
        /// </summary>
        public static string titleExpandthisbranch {
            get {
                return ResourceManager.GetString("titleExpandthisbranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FamilyTree.
        /// </summary>
        public static string titleFamilyTree {
            get {
                return ResourceManager.GetString("titleFamilyTree", resourceCulture);
            }
        }
    }
}
