//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBISCCMWeb.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SBISCCMWeb.LanguageResources.DandB.HomeLang", typeof(HomeLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Usage Statistics.
        /// </summary>
        public static string hdrAPIUsageStatistics {
            get {
                return ResourceManager.GetString("hdrAPIUsageStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Process Logs.
        /// </summary>
        public static string hdrBackgroundProcessLogs {
            get {
                return ResourceManager.GetString("hdrBackgroundProcessLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Enrichment.
        /// </summary>
        public static string hdrDataEnrichment {
            get {
                return ResourceManager.GetString("hdrDataEnrichment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Queue Statistics.
        /// </summary>
        public static string hdrDataQueueStatistics {
            get {
                return ResourceManager.GetString("hdrDataQueueStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Stewardship Queue.
        /// </summary>
        public static string hdrDataStewardshipQueue {
            get {
                return ResourceManager.GetString("hdrDataStewardshipQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrichment.
        /// </summary>
        public static string hdrEnrichment {
            get {
                return ResourceManager.GetString("hdrEnrichment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Queue.
        /// </summary>
        public static string hdrExportQueue {
            get {
                return ResourceManager.GetString("hdrExportQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity Resolution.
        /// </summary>
        public static string hdrIdentityResolution {
            get {
                return ResourceManager.GetString("hdrIdentityResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Process Queue.
        /// </summary>
        public static string hdrImportProcessQueue {
            get {
                return ResourceManager.GetString("hdrImportProcessQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Queue.
        /// </summary>
        public static string hdrImportQueue {
            get {
                return ResourceManager.GetString("hdrImportQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Queue.
        /// </summary>
        public static string hdrInputQueue {
            get {
                return ResourceManager.GetString("hdrInputQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investigation Report.
        /// </summary>
        public static string hdrInvestigationReport {
            get {
                return ResourceManager.GetString("hdrInvestigationReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring Notification.
        /// </summary>
        public static string hdrMonitoringNotification {
            get {
                return ResourceManager.GetString("hdrMonitoringNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Details.
        /// </summary>
        public static string hdrProfileDetails {
            get {
                return ResourceManager.GetString("hdrProfileDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string hdrResetPassword {
            get {
                return ResourceManager.GetString("hdrResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Question and Answer.
        /// </summary>
        public static string hdrSecurityQuestionandAnswer {
            get {
                return ResourceManager.GetString("hdrSecurityQuestionandAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string lblAbout {
            get {
                return ResourceManager.GetString("lblAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Records.
        /// </summary>
        public static string lblActiveRecords {
            get {
                return ResourceManager.GetString("lblActiveRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this area to provide additional information..
        /// </summary>
        public static string lblAdditionalInformation {
            get {
                return ResourceManager.GetString("lblAdditionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string lblAll {
            get {
                return ResourceManager.GetString("lblAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Candidates.
        /// </summary>
        public static string lblAllCandidates {
            get {
                return ResourceManager.GetString("lblAllCandidates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt. Lookup.
        /// </summary>
        public static string lblAltLookup {
            get {
                return ResourceManager.GetString("lblAltLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string lblApply {
            get {
                return ResourceManager.GetString("lblApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archival.
        /// </summary>
        public static string lblArchival {
            get {
                return ResourceManager.GetString("lblArchival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archival Queue Count.
        /// </summary>
        public static string lblArchivalQueueCount {
            get {
                return ResourceManager.GetString("lblArchivalQueueCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg Resolution Time.
        /// </summary>
        public static string lblAvgResolutionTime {
            get {
                return ResourceManager.GetString("lblAvgResolutionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg-time.
        /// </summary>
        public static string lblAvgTime {
            get {
                return ResourceManager.GetString("lblAvgTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note : Statistics based on last 48 hours of data.
        /// </summary>
        public static string lblBackgroundStatsNote {
            get {
                return ResourceManager.GetString("lblBackgroundStatsNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Image.
        /// </summary>
        public static string lblChangeImage {
            get {
                return ResourceManager.GetString("lblChangeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleanse Match.
        /// </summary>
        public static string lblCleanseMatch {
            get {
                return ResourceManager.GetString("lblCleanseMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string lblClear {
            get {
                return ResourceManager.GetString("lblClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed Cases.
        /// </summary>
        public static string lblClosedCases {
            get {
                return ResourceManager.GetString("lblClosedCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string lblConfirmPassword {
            get {
                return ResourceManager.GetString("lblConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string lblContinue {
            get {
                return ResourceManager.GetString("lblContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Month.
        /// </summary>
        public static string lblCurrentMonth {
            get {
                return ResourceManager.GetString("lblCurrentMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current UTC Time.
        /// </summary>
        public static string lblCurrentUTCTime {
            get {
                return ResourceManager.GetString("lblCurrentUTCTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Enrichment.
        /// </summary>
        public static string lblDataEnrichment {
            get {
                return ResourceManager.GetString("lblDataEnrichment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Time.
        /// </summary>
        public static string lblDateTime {
            get {
                return ResourceManager.GetString("lblDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DUNS.
        /// </summary>
        public static string lblDUNS {
            get {
                return ResourceManager.GetString("lblDUNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string lblDuration {
            get {
                return ResourceManager.GetString("lblDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration Hours.
        /// </summary>
        public static string lblDurationHours {
            get {
                return ResourceManager.GetString("lblDurationHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string lblEmailAddress {
            get {
                return ResourceManager.GetString("lblEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrichment output.
        /// </summary>
        public static string lblEnrichment_output {
            get {
                return ResourceManager.GetString("lblEnrichment_output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrichment    Output.
        /// </summary>
        public static string lblEnrichmentOutput {
            get {
                return ResourceManager.GetString("lblEnrichmentOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrichment Processing.
        /// </summary>
        public static string lblEnrichmentProcessing {
            get {
                return ResourceManager.GetString("lblEnrichmentProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrichment Queue Count.
        /// </summary>
        public static string lblEnrichmentQueueCount {
            get {
                return ResourceManager.GetString("lblEnrichmentQueueCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETL Details.
        /// </summary>
        public static string lblETLDetails {
            get {
                return ResourceManager.GetString("lblETLDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETL Type.
        /// </summary>
        public static string lblETLType {
            get {
                return ResourceManager.GetString("lblETLType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution Id.
        /// </summary>
        public static string lblExecutionId {
            get {
                return ResourceManager.GetString("lblExecutionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string lblFailed {
            get {
                return ResourceManager.GetString("lblFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Import.
        /// </summary>
        public static string lblFileImport {
            get {
                return ResourceManager.GetString("lblFileImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string lblFiles {
            get {
                return ResourceManager.GetString("lblFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered.
        /// </summary>
        public static string lblFiltered {
            get {
                return ResourceManager.GetString("lblFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a verification code via email..
        /// </summary>
        public static string lblGetVerificationCode {
            get {
                return ResourceManager.GetString("lblGetVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HQ/SL Records.
        /// </summary>
        public static string lblHQSLRecords {
            get {
                return ResourceManager.GetString("lblHQSLRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I accept.
        /// </summary>
        public static string lblIAccept {
            get {
                return ResourceManager.GetString("lblIAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string lblImport {
            get {
                return ResourceManager.GetString("lblImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Date.
        /// </summary>
        public static string lblImportDate {
            get {
                return ResourceManager.GetString("lblImportDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported Row.
        /// </summary>
        public static string lblImportedRow {
            get {
                return ResourceManager.GetString("lblImportedRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Process.
        /// </summary>
        public static string lblImportProcess {
            get {
                return ResourceManager.GetString("lblImportProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure to include at least 3 rules..
        /// </summary>
        public static string lblIncludeThreeRules {
            get {
                return ResourceManager.GetString("lblIncludeThreeRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string lblInput {
            get {
                return ResourceManager.GetString("lblInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Queue Count.
        /// </summary>
        public static string lblInputQueueCount {
            get {
                return ResourceManager.GetString("lblInputQueueCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Record.
        /// </summary>
        public static string lblInputRecord {
            get {
                return ResourceManager.GetString("lblInputRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOB Tag.
        /// </summary>
        public static string lblLOBTag {
            get {
                return ResourceManager.GetString("lblLOBTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Confidence.
        /// </summary>
        public static string lblLowConfidence {
            get {
                return ResourceManager.GetString("lblLowConfidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Confidence Queue Count.
        /// </summary>
        public static string lblLowConfidenceQueueCount {
            get {
                return ResourceManager.GetString("lblLowConfidenceQueueCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowercase.
        /// </summary>
        public static string lblLowercase {
            get {
                return ResourceManager.GetString("lblLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match output.
        /// </summary>
        public static string lblMatch_output {
            get {
                return ResourceManager.GetString("lblMatch_output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match  Output.
        /// </summary>
        public static string lblMatchOutput {
            get {
                return ResourceManager.GetString("lblMatchOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Processing.
        /// </summary>
        public static string lblMatchProcessing {
            get {
                return ResourceManager.GetString("lblMatchProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max-time.
        /// </summary>
        public static string lblMaxTime {
            get {
                return ResourceManager.GetString("lblMaxTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string lblMesage {
            get {
                return ResourceManager.GetString("lblMesage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password should be a minimum of 8 characters long.
        /// </summary>
        public static string lblMinimumPasswordLength {
            get {
                return ResourceManager.GetString("lblMinimumPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min-time.
        /// </summary>
        public static string lblMinTime {
            get {
                return ResourceManager.GetString("lblMinTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Address Lookup.
        /// </summary>
        public static string lblNameAddressLookup {
            get {
                return ResourceManager.GetString("lblNameAddressLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Execution.
        /// </summary>
        public static string lblNextExecution {
            get {
                return ResourceManager.GetString("lblNextExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data are available.
        /// </summary>
        public static string lblNoDataAreAvailable {
            get {
                return ResourceManager.GetString("lblNoDataAreAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data are available.
        /// </summary>
        public static string lblNodataareavailableMessage {
            get {
                return ResourceManager.GetString("lblNodataareavailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data are available.
        /// </summary>
        public static string lblNoDataAvailable {
            get {
                return ResourceManager.GetString("lblNoDataAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data are available.
        /// </summary>
        public static string lblNoDatasAvailable {
            get {
                return ResourceManager.GetString("lblNoDatasAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Match.
        /// </summary>
        public static string lblNoMatch {
            get {
                return ResourceManager.GetString("lblNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoMatch Queue Count.
        /// </summary>
        public static string lblNoMatchQueueCount {
            get {
                return ResourceManager.GetString("lblNoMatchQueueCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string lblNumber {
            get {
                return ResourceManager.GetString("lblNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Cases.
        /// </summary>
        public static string lblOpenCases {
            get {
                return ResourceManager.GetString("lblOpenCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened Last Week.
        /// </summary>
        public static string lblOpenedLastWeek {
            get {
                return ResourceManager.GetString("lblOpenedLastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Queue Count.
        /// </summary>
        public static string lblOutputQueueCount {
            get {
                return ResourceManager.GetString("lblOutputQueueCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Password must be at least 8 characters long, contain alpha numeric characters and atleast one special character..
        /// </summary>
        public static string lblPasswordLimit {
            get {
                return ResourceManager.GetString("lblPasswordLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Process Record Count.
        /// </summary>
        public static string lblPendingProcessRecordCount {
            get {
                return ResourceManager.GetString("lblPendingProcessRecordCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Complete.
        /// </summary>
        public static string lblProcessComplete {
            get {
                return ResourceManager.GetString("lblProcessComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed Record Count.
        /// </summary>
        public static string lblProcessedRecordCount {
            get {
                return ResourceManager.GetString("lblProcessedRecordCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while processing....
        /// </summary>
        public static string lblProcessing {
            get {
                return ResourceManager.GetString("lblProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Queue Count.
        /// </summary>
        public static string lblProcessingQueueCount {
            get {
                return ResourceManager.GetString("lblProcessingQueueCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Status.
        /// </summary>
        public static string lblProcessStatus {
            get {
                return ResourceManager.GetString("lblProcessStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Type.
        /// </summary>
        public static string lblProcessType {
            get {
                return ResourceManager.GetString("lblProcessType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me on this machine(Do not select this option if you are logging in from a public machine).
        /// </summary>
        public static string lblRememberOnMachine {
            get {
                return ResourceManager.GetString("lblRememberOnMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not remember your security question?.
        /// </summary>
        public static string lblRememberSecurityQuestion {
            get {
                return ResourceManager.GetString("lblRememberSecurityQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Image.
        /// </summary>
        public static string lblRemoveImage {
            get {
                return ResourceManager.GetString("lblRemoveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string lblResetPassword {
            get {
                return ResourceManager.GetString("lblResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string lblSearch {
            get {
                return ResourceManager.GetString("lblSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Answer.
        /// </summary>
        public static string lblSecurityAnswer {
            get {
                return ResourceManager.GetString("lblSecurityAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Question.
        /// </summary>
        public static string lblSecurityQuestion {
            get {
                return ResourceManager.GetString("lblSecurityQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Character.
        /// </summary>
        public static string lblSpecialCharacter {
            get {
                return ResourceManager.GetString("lblSpecialCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Type.
        /// </summary>
        public static string lblStatusType {
            get {
                return ResourceManager.GetString("lblStatusType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string lblSubmit {
            get {
                return ResourceManager.GetString("lblSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string lblTag {
            get {
                return ResourceManager.GetString("lblTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string lblTags {
            get {
                return ResourceManager.GetString("lblTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Candidates.
        /// </summary>
        public static string lblTopCandidates {
            get {
                return ResourceManager.GetString("lblTopCandidates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string lblTotal {
            get {
                return ResourceManager.GetString("lblTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Matched.
        /// </summary>
        public static string lblTotalMatched {
            get {
                return ResourceManager.GetString("lblTotalMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Records.
        /// </summary>
        public static string lblTotalRecords {
            get {
                return ResourceManager.GetString("lblTotalRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under Investigation.
        /// </summary>
        public static string lblUnderInvestigation {
            get {
                return ResourceManager.GetString("lblUnderInvestigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Security Answer.
        /// </summary>
        public static string lblUpdateSecurityAnswer {
            get {
                return ResourceManager.GetString("lblUpdateSecurityAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Image.
        /// </summary>
        public static string lblUploadImage {
            get {
                return ResourceManager.GetString("lblUploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uppercase.
        /// </summary>
        public static string lblUppercase {
            get {
                return ResourceManager.GetString("lblUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string lblUserName {
            get {
                return ResourceManager.GetString("lblUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YTD.
        /// </summary>
        public static string lblYTD {
            get {
                return ResourceManager.GetString("lblYTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string lbPassword {
            get {
                return ResourceManager.GetString("lbPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only formats allowed are :jpeg, jpg, png, gif, bmp.
        /// </summary>
        public static string msgAllowedFormats {
            get {
                return ResourceManager.GetString("msgAllowedFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only formats allowed are :.
        /// </summary>
        public static string msgAllowedFormatsOnly {
            get {
                return ResourceManager.GetString("msgAllowedFormatsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration(In seconds).
        /// </summary>
        public static string msgDurationInSeconds {
            get {
                return ResourceManager.GetString("msgDurationInSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches.
        /// </summary>
        public static string msgMatches {
            get {
                return ResourceManager.GetString("msgMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches by Confidence Code.
        /// </summary>
        public static string msgMatchesByConfidenceCode {
            get {
                return ResourceManager.GetString("msgMatchesByConfidenceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches by Users.
        /// </summary>
        public static string msgMatchesByUsers {
            get {
                return ResourceManager.GetString("msgMatchesByUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure, you want to pause setting ?.
        /// </summary>
        public static string msgPauseSetting {
            get {
                return ResourceManager.GetString("msgPauseSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Stats.
        /// </summary>
        public static string msgProcessStats {
            get {
                return ResourceManager.GetString("msgProcessStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records.
        /// </summary>
        public static string msgRecords {
            get {
                return ResourceManager.GetString("msgRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove data from file ?.
        /// </summary>
        public static string msgRemoveDataFromFile {
            get {
                return ResourceManager.GetString("msgRemoveDataFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this image?.
        /// </summary>
        public static string msgRemoveImage {
            get {
                return ResourceManager.GetString("msgRemoveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not specified a file..
        /// </summary>
        public static string msgSpecifyFile {
            get {
                return ResourceManager.GetString("msgSpecifyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure, you want to un-pause setting ?.
        /// </summary>
        public static string msgUnpauseSetting {
            get {
                return ResourceManager.GetString("msgUnpauseSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File uploaded successfully..
        /// </summary>
        public static string msgUploadFile {
            get {
                return ResourceManager.GetString("msgUploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security answer.
        /// </summary>
        public static string placeholderSecurityanswer {
            get {
                return ResourceManager.GetString("placeholderSecurityanswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Queue Statistics By ImportProcess.
        /// </summary>
        public static string spnByImportProcess {
            get {
                return ResourceManager.GetString("spnByImportProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Tags.
        /// </summary>
        public static string spnByTags {
            get {
                return ResourceManager.GetString("spnByTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Status.
        /// </summary>
        public static string String12 {
            get {
                return ResourceManager.GetString("String12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Records.
        /// </summary>
        public static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Time.
        /// </summary>
        public static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matchbook | About.
        /// </summary>
        public static string titleAbout {
            get {
                return ResourceManager.GetString("titleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Data Queue Detail Report.
        /// </summary>
        public static string titleActiveDataQueueDetailReport {
            get {
                return ResourceManager.GetString("titleActiveDataQueueDetailReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Data Queue Statistics.
        /// </summary>
        public static string titleActiveDataQueueStatistics {
            get {
                return ResourceManager.GetString("titleActiveDataQueueStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Usage Statistics.
        /// </summary>
        public static string titleAPIUsageStatistics {
            get {
                return ResourceManager.GetString("titleAPIUsageStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Process Statistics.
        /// </summary>
        public static string titleBackgroundProcessStatistics {
            get {
                return ResourceManager.GetString("titleBackgroundProcessStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string titleDashboard {
            get {
                return ResourceManager.GetString("titleDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Stewardship Statistics.
        /// </summary>
        public static string titleDataStewardshipStatistics {
            get {
                return ResourceManager.GetString("titleDataStewardshipStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail Statistics Report.
        /// </summary>
        public static string titleDetailStatisticsReport {
            get {
                return ResourceManager.GetString("titleDetailStatisticsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Data Queue Statistics.
        /// </summary>
        public static string titleDownloadDataQueueStatistics {
            get {
                return ResourceManager.GetString("titleDownloadDataQueueStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Confidence Match Candidate Statistics.
        /// </summary>
        public static string titleLCMCandidateStatistics {
            get {
                return ResourceManager.GetString("titleLCMCandidateStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Details.
        /// </summary>
        public static string titleProcessDetails {
            get {
                return ResourceManager.GetString("titleProcessDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Queue.
        /// </summary>
        public static string titleProcessingQueue {
            get {
                return ResourceManager.GetString("titleProcessingQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string titleProfile {
            get {
                return ResourceManager.GetString("titleProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Active Data Queue Statistics.
        /// </summary>
        public static string titleRefreshActiveDataQueueStatistics {
            get {
                return ResourceManager.GetString("titleRefreshActiveDataQueueStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Background Process Statistics.
        /// </summary>
        public static string titleRefreshBackgroundProcessStatistics {
            get {
                return ResourceManager.GetString("titleRefreshBackgroundProcessStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Data Stewardship Statistics.
        /// </summary>
        public static string titleRefreshDataStewardshipStatistics {
            get {
                return ResourceManager.GetString("titleRefreshDataStewardshipStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Low Confidence Match Candidate Statistics.
        /// </summary>
        public static string titleRefreshLowConfidenceMatchCandidateStatistics {
            get {
                return ResourceManager.GetString("titleRefreshLowConfidenceMatchCandidateStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string titleResetPassword {
            get {
                return ResourceManager.GetString("titleResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User License Agreement.
        /// </summary>
        public static string titleUserLicenseAgreement {
            get {
                return ResourceManager.GetString("titleUserLicenseAgreement", resourceCulture);
            }
        }
    }
}
