//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBISCCMWeb.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class iResearchInvestigationLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal iResearchInvestigationLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SBISCCMWeb.LanguageResources.DandB.iResearchInvestigationLang", typeof(iResearchInvestigationLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Information.
        /// </summary>
        public static string hdrBasicInformation {
            get {
                return ResourceManager.GetString("hdrBasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D&amp;B iResearch Investigation.
        /// </summary>
        public static string hdrDAndBiResearch {
            get {
                return ResourceManager.GetString("hdrDAndBiResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D&amp;B iResearch: Mini Investigation.
        /// </summary>
        public static string hdrDAndBiResearchMini {
            get {
                return ResourceManager.GetString("hdrDAndBiResearchMini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D&amp;B iResearch: Targeted Investigation.
        /// </summary>
        public static string hdrDAndBiResearchTargeted {
            get {
                return ResourceManager.GetString("hdrDAndBiResearchTargeted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate DUNS.
        /// </summary>
        public static string hdrDuplicateDUNS {
            get {
                return ResourceManager.GetString("hdrDuplicateDUNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investigation Column Mapping.
        /// </summary>
        public static string hdrInvestigationColumnMapping {
            get {
                return ResourceManager.GetString("hdrInvestigationColumnMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investigation Details.
        /// </summary>
        public static string hdrInvestigationDetails {
            get {
                return ResourceManager.GetString("hdrInvestigationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investigation File Upload.
        /// </summary>
        public static string hdrInvestigationFileUpload {
            get {
                return ResourceManager.GetString("hdrInvestigationFileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mini Investigation.
        /// </summary>
        public static string hdrMiniInvestigation {
            get {
                return ResourceManager.GetString("hdrMiniInvestigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Details.
        /// </summary>
        public static string hdrRequestDetails {
            get {
                return ResourceManager.GetString("hdrRequestDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Details.
        /// </summary>
        public static string hdrResponseDetails {
            get {
                return ResourceManager.GetString("hdrResponseDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string lblAction {
            get {
                return ResourceManager.GetString("lblAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Actions.
        /// </summary>
        public static string lblAdditionalActions {
            get {
                return ResourceManager.GetString("lblAdditionalActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string lblAddress {
            get {
                return ResourceManager.GetString("lblAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg. Resolution Time(In days).
        /// </summary>
        public static string lblAvgResolutionTime {
            get {
                return ResourceManager.GetString("lblAvgResolutionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Investigation.
        /// </summary>
        public static string lblBulkInvestigation {
            get {
                return ResourceManager.GetString("lblBulkInvestigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Mini Investigation.
        /// </summary>
        public static string lblBulkMiniInvestigation {
            get {
                return ResourceManager.GetString("lblBulkMiniInvestigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Targeted Investigation.
        /// </summary>
        public static string lblBulkTargetedInvestigation {
            get {
                return ResourceManager.GetString("lblBulkTargetedInvestigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Name.
        /// </summary>
        public static string lblBusinessName {
            get {
                return ResourceManager.GetString("lblBusinessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string lblCancel {
            get {
                return ResourceManager.GetString("lblCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Id.
        /// </summary>
        public static string lblCaseId {
            get {
                return ResourceManager.GetString("lblCaseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Resolution.
        /// </summary>
        public static string lblCaseResolution {
            get {
                return ResourceManager.GetString("lblCaseResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case status.
        /// </summary>
        public static string lblCasestatus {
            get {
                return ResourceManager.GetString("lblCasestatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge.
        /// </summary>
        public static string lblChallenge {
            get {
                return ResourceManager.GetString("lblChallenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge Investigation.
        /// </summary>
        public static string lblChallengeInvestigation {
            get {
                return ResourceManager.GetString("lblChallengeInvestigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge Reason.
        /// </summary>
        public static string lblChallengeReason {
            get {
                return ResourceManager.GetString("lblChallengeReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string lblCity {
            get {
                return ResourceManager.GetString("lblCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Cases.
        /// </summary>
        public static string lblCloseCases {
            get {
                return ResourceManager.GetString("lblCloseCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string lblCompany {
            get {
                return ResourceManager.GetString("lblCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string lblCountry {
            get {
                return ResourceManager.GetString("lblCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country ISO Code.
        /// </summary>
        public static string lblCountryISOCode {
            get {
                return ResourceManager.GetString("lblCountryISOCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Reference.
        /// </summary>
        public static string lblCustomerReference {
            get {
                return ResourceManager.GetString("lblCustomerReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Transaction ID.
        /// </summary>
        public static string lblCustomerTransactionID {
            get {
                return ResourceManager.GetString("lblCustomerTransactionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string lblDate {
            get {
                return ResourceManager.GetString("lblDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string lblDetails {
            get {
                return ResourceManager.GetString("lblDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Template.
        /// </summary>
        public static string lblDownloadSamplefile {
            get {
                return ResourceManager.GetString("lblDownloadSamplefile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DUNS.
        /// </summary>
        public static string lblDUNS {
            get {
                return ResourceManager.GetString("lblDUNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DUNS Number.
        /// </summary>
        public static string lblDUNSNumber {
            get {
                return ResourceManager.GetString("lblDUNSNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DUNS Number1.
        /// </summary>
        public static string lblDUNSNumber1 {
            get {
                return ResourceManager.GetString("lblDUNSNumber1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DUNS Number2.
        /// </summary>
        public static string lblDUNSNumber2 {
            get {
                return ResourceManager.GetString("lblDUNSNumber2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DUNS Number3.
        /// </summary>
        public static string lblDUNSNumber3 {
            get {
                return ResourceManager.GetString("lblDUNSNumber3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DUNS Number4.
        /// </summary>
        public static string lblDUNSNumber4 {
            get {
                return ResourceManager.GetString("lblDUNSNumber4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DUNS Number5.
        /// </summary>
        public static string lblDUNSNumber5 {
            get {
                return ResourceManager.GetString("lblDUNSNumber5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Duns.
        /// </summary>
        public static string lblDuplicateDuns {
            get {
                return ResourceManager.GetString("lblDuplicateDuns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string lblEdit {
            get {
                return ResourceManager.GetString("lblEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error message.
        /// </summary>
        public static string lblErrormessage {
            get {
                return ResourceManager.GetString("lblErrormessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        public static string lblExample {
            get {
                return ResourceManager.GetString("lblExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to CSV.
        /// </summary>
        public static string lblExportToCSV {
            get {
                return ResourceManager.GetString("lblExportToCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Cases.
        /// </summary>
        public static string lblFailedCases {
            get {
                return ResourceManager.GetString("lblFailedCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File (Accepts only Excel files).
        /// </summary>
        public static string lblFileAccepts {
            get {
                return ResourceManager.GetString("lblFileAccepts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get status for all.
        /// </summary>
        public static string lblGetAllStatus {
            get {
                return ResourceManager.GetString("lblGetAllStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Status.
        /// </summary>
        public static string lblGetStatus {
            get {
                return ResourceManager.GetString("lblGetStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        public static string lblHerelink {
            get {
                return ResourceManager.GetString("lblHerelink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Header.
        /// </summary>
        public static string lblInputHeader {
            get {
                return ResourceManager.GetString("lblInputHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investigation Status.
        /// </summary>
        public static string lblInvestigationStatus {
            get {
                return ResourceManager.GetString("lblInvestigationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note : Mini Research focuses on the assignment of DUNS Numbers to Business Entities validating basic firmographic details..
        /// </summary>
        public static string lbliResearchNote {
            get {
                return ResourceManager.GetString("lbliResearchNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note : Targeted Investigation focuses on the updating an existing business using specific data categories such as “Address”, “Line Of Business”, etc..
        /// </summary>
        public static string lbliResearchTargetedNote {
            get {
                return ResourceManager.GetString("lbliResearchTargetedNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsActive.
        /// </summary>
        public static string lblIsActive {
            get {
                return ResourceManager.GetString("lblIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword.
        /// </summary>
        public static string lblKeyword {
            get {
                return ResourceManager.GetString("lblKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string lblMessage {
            get {
                return ResourceManager.GetString("lblMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mini Investigation.
        /// </summary>
        public static string lblMiniInvestigation {
            get {
                return ResourceManager.GetString("lblMiniInvestigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Record(s) found.
        /// </summary>
        public static string lblNoRecords {
            get {
                return ResourceManager.GetString("lblNoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened Cases.
        /// </summary>
        public static string lblOpenCases {
            get {
                return ResourceManager.GetString("lblOpenCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string lblPostalCode {
            get {
                return ResourceManager.GetString("lblPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Address.
        /// </summary>
        public static string lblPrimaryAddress {
            get {
                return ResourceManager.GetString("lblPrimaryAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Name.
        /// </summary>
        public static string lblPrimaryName {
            get {
                return ResourceManager.GetString("lblPrimaryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Status.
        /// </summary>
        public static string lblRefreshStatus {
            get {
                return ResourceManager.GetString("lblRefreshStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested DateTime.
        /// </summary>
        public static string lblRequestedDateTime {
            get {
                return ResourceManager.GetString("lblRequestedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requestor Email.
        /// </summary>
        public static string lblRequestorEmail {
            get {
                return ResourceManager.GetString("lblRequestorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requestor Email Address.
        /// </summary>
        public static string lblRequestorEmailAddress {
            get {
                return ResourceManager.GetString("lblRequestorEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Type.
        /// </summary>
        public static string lblRequestType {
            get {
                return ResourceManager.GetString("lblRequestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BusinessName number is required.
        /// </summary>
        public static string lblRequiredBusinessName {
            get {
                return ResourceManager.GetString("lblRequiredBusinessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City is required.
        /// </summary>
        public static string lblRequiredCity {
            get {
                return ResourceManager.GetString("lblRequiredCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research Comment is required.
        /// </summary>
        public static string lblRequiredComment {
            get {
                return ResourceManager.GetString("lblRequiredComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country ISO Code is required.
        /// </summary>
        public static string lblRequiredCountryISOCode {
            get {
                return ResourceManager.GetString("lblRequiredCountryISOCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DUNS number is required.
        /// </summary>
        public static string lblRequiredDUNS {
            get {
                return ResourceManager.GetString("lblRequiredDUNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid RequestorEmail.
        /// </summary>
        public static string lblRequiredEmail {
            get {
                return ResourceManager.GetString("lblRequiredEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostalCode is required.
        /// </summary>
        public static string lblRequiredPostalCode {
            get {
                return ResourceManager.GetString("lblRequiredPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research Comment (Financial Figures) is required.
        /// </summary>
        public static string lblRequiredResearchComment1 {
            get {
                return ResourceManager.GetString("lblRequiredResearchComment1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research Comments (Financial Ratios) is required.
        /// </summary>
        public static string lblRequiredResearchComment2 {
            get {
                return ResourceManager.GetString("lblRequiredResearchComment2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research Comments is required..
        /// </summary>
        public static string lblRequiredResearchComments {
            get {
                return ResourceManager.GetString("lblRequiredResearchComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research Sub Types is required.
        /// </summary>
        public static string lblRequiredResearchSubTypes {
            get {
                return ResourceManager.GetString("lblRequiredResearchSubTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StreetAdderss is required.
        /// </summary>
        public static string lblRequiredStreetAdderss {
            get {
                return ResourceManager.GetString("lblRequiredStreetAdderss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research comment.
        /// </summary>
        public static string lblResearchcomment {
            get {
                return ResourceManager.GetString("lblResearchcomment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research Comments.
        /// </summary>
        public static string lblResearchComments {
            get {
                return ResourceManager.GetString("lblResearchComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research Comment (Financial Figures).
        /// </summary>
        public static string lblResearchComments1 {
            get {
                return ResourceManager.GetString("lblResearchComments1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research Comments (Financial Ratios).
        /// </summary>
        public static string lblResearchComments2 {
            get {
                return ResourceManager.GetString("lblResearchComments2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research RequestID.
        /// </summary>
        public static string lblResearchRequestID {
            get {
                return ResourceManager.GetString("lblResearchRequestID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research Subtype.
        /// </summary>
        public static string lblResearchSubtype {
            get {
                return ResourceManager.GetString("lblResearchSubtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research Subtype Information.
        /// </summary>
        public static string lblResearchSubtypeInformation {
            get {
                return ResourceManager.GetString("lblResearchSubtypeInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research Sub Types.
        /// </summary>
        public static string lblResearchSubTypes {
            get {
                return ResourceManager.GetString("lblResearchSubTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution Date.
        /// </summary>
        public static string lblResolutionDate {
            get {
                return ResourceManager.GetString("lblResolutionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution DUNS.
        /// </summary>
        public static string lblResolutionDUNS {
            get {
                return ResourceManager.GetString("lblResolutionDUNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string lblSearch {
            get {
                return ResourceManager.GetString("lblSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Src Id.
        /// </summary>
        public static string lblSrcId {
            get {
                return ResourceManager.GetString("lblSrcId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SrcRecordId.
        /// </summary>
        public static string lblSrcRecordId {
            get {
                return ResourceManager.GetString("lblSrcRecordId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string lblState {
            get {
                return ResourceManager.GetString("lblState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string lblStatus {
            get {
                return ResourceManager.GetString("lblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Address.
        /// </summary>
        public static string lblStreetAddress {
            get {
                return ResourceManager.GetString("lblStreetAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string lblSubmit {
            get {
                return ResourceManager.GetString("lblSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted Date.
        /// </summary>
        public static string lblSubmittedDate {
            get {
                return ResourceManager.GetString("lblSubmittedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Column.
        /// </summary>
        public static string lblTableColumn {
            get {
                return ResourceManager.GetString("lblTableColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targeted Investigation.
        /// </summary>
        public static string lblTargetedInvestigation {
            get {
                return ResourceManager.GetString("lblTargetedInvestigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Cases.
        /// </summary>
        public static string lblTotalCases {
            get {
                return ResourceManager.GetString("lblTotalCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TradeStyle Name.
        /// </summary>
        public static string lblTradeStyleName {
            get {
                return ResourceManager.GetString("lblTradeStyleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string lblUpdate {
            get {
                return ResourceManager.GetString("lblUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Status.
        /// </summary>
        public static string lblUpdateStatus {
            get {
                return ResourceManager.GetString("lblUpdateStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip.
        /// </summary>
        public static string lblZip {
            get {
                return ResourceManager.GetString("lblZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to already belongs to this file.
        /// </summary>
        public static string msgAlreadyBelongsToFile {
            get {
                return ResourceManager.GetString("msgAlreadyBelongsToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid email address..
        /// </summary>
        public static string msgEnterValidEmail {
            get {
                return ResourceManager.GetString("msgEnterValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:.
        /// </summary>
        public static string msgError {
            get {
                return ResourceManager.GetString("msgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investigation record does not submitted successfully. Please try again.
        /// </summary>
        public static string msgInsertFailInvestigation {
            get {
                return ResourceManager.GetString("msgInsertFailInvestigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The investigation request was completed successfully..
        /// </summary>
        public static string msgInsertInvestigation {
            get {
                return ResourceManager.GetString("msgInsertInvestigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while challenging the investigation..
        /// </summary>
        public static string msgInvestigationChallengedFailed {
            get {
                return ResourceManager.GetString("msgInvestigationChallengedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investigation challenged successfully..
        /// </summary>
        public static string msgInvestigationChallengedSuccess {
            get {
                return ResourceManager.GetString("msgInvestigationChallengedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only formats allowed are : txt.
        /// </summary>
        public static string msgInvestigationFileFormat {
            get {
                return ResourceManager.GetString("msgInvestigationFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investigation received successfully.
        /// </summary>
        public static string msgInvestigationReceived {
            get {
                return ResourceManager.GetString("msgInvestigationReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investigation not received successfully.
        /// </summary>
        public static string msgInvestigationReceivedFail {
            get {
                return ResourceManager.GetString("msgInvestigationReceivedFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records available on this page..
        /// </summary>
        public static string msgNoRecordsAvailable {
            get {
                return ResourceManager.GetString("msgNoRecordsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only formats allowed are.xls and.xlsx.
        /// </summary>
        public static string msgOnlyExcelAllowed {
            get {
                return ResourceManager.GetString("msgOnlyExcelAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only formats allowed are :.
        /// </summary>
        public static string msgOnlyFormatsAllowed {
            get {
                return ResourceManager.GetString("msgOnlyFormatsAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requestor Email is required..
        /// </summary>
        public static string msgRequiredRequestorEmail {
            get {
                return ResourceManager.GetString("msgRequiredRequestorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select file first..
        /// </summary>
        public static string msgSelectFile {
            get {
                return ResourceManager.GetString("msgSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To submit Targeted Investigation Research Subtype is required. Please download Research Subtype information from.
        /// </summary>
        public static string msgTargetedResearchSubTypeNote {
            get {
                return ResourceManager.GetString("msgTargetedResearchSubTypeNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to import blank file.
        /// </summary>
        public static string msgUnableImportBlankFile {
            get {
                return ResourceManager.GetString("msgUnableImportBlankFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The investigation request was updated successfully..
        /// </summary>
        public static string msgUpdateInvestigation {
            get {
                return ResourceManager.GetString("msgUpdateInvestigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iResearch Investigation.
        /// </summary>
        public static string titleiResearchInvestigation {
            get {
                return ResourceManager.GetString("titleiResearchInvestigation", resourceCulture);
            }
        }
    }
}
