//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBISCCMWeb.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OIHomeLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OIHomeLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SBISCCMWeb.LanguageResources.OI.OIHomeLang", typeof(OIHomeLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Queue Statistics.
        /// </summary>
        public static string hdrDataQueueStatistics {
            get {
                return ResourceManager.GetString("hdrDataQueueStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Usage.
        /// </summary>
        public static string lblAPIUsage {
            get {
                return ResourceManager.GetString("lblAPIUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archival Queue Count.
        /// </summary>
        public static string lblArchivalQueueCount {
            get {
                return ResourceManager.GetString("lblArchivalQueueCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Process.
        /// </summary>
        public static string lblBackgroundProcess {
            get {
                return ResourceManager.GetString("lblBackgroundProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Tree.
        /// </summary>
        public static string lblCompanyTree {
            get {
                return ResourceManager.GetString("lblCompanyTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Month.
        /// </summary>
        public static string lblCurrentMonth {
            get {
                return ResourceManager.GetString("lblCurrentMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Queue.
        /// </summary>
        public static string lblDataQueue {
            get {
                return ResourceManager.GetString("lblDataQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmographics.
        /// </summary>
        public static string lblFirmographics {
            get {
                return ResourceManager.GetString("lblFirmographics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmographics Export Queue Count.
        /// </summary>
        public static string lblFirmographicsExportQueueCount {
            get {
                return ResourceManager.GetString("lblFirmographicsExportQueueCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Date.
        /// </summary>
        public static string lblImportDate {
            get {
                return ResourceManager.GetString("lblImportDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Process.
        /// </summary>
        public static string lblImportProcess {
            get {
                return ResourceManager.GetString("lblImportProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string lblInput {
            get {
                return ResourceManager.GetString("lblInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 24 Hours.
        /// </summary>
        public static string lblLast24Hours {
            get {
                return ResourceManager.GetString("lblLast24Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matched Output Queue Count.
        /// </summary>
        public static string lblMatchedOutputQueueCount {
            get {
                return ResourceManager.GetString("lblMatchedOutputQueueCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match/Enrich Process.
        /// </summary>
        public static string lblMatchEnrichProcess {
            get {
                return ResourceManager.GetString("lblMatchEnrichProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Output.
        /// </summary>
        public static string lblMatchOutput {
            get {
                return ResourceManager.GetString("lblMatchOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data are available.
        /// </summary>
        public static string lblNodataareavailable {
            get {
                return ResourceManager.GetString("lblNodataareavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Records.
        /// </summary>
        public static string lblTotalRecords {
            get {
                return ResourceManager.GetString("lblTotalRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnMatched.
        /// </summary>
        public static string lblUnMatched {
            get {
                return ResourceManager.GetString("lblUnMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnMatched Record Count.
        /// </summary>
        public static string lblUnMatchedRecordCount {
            get {
                return ResourceManager.GetString("lblUnMatchedRecordCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLEANSE MATCH.
        /// </summary>
        public static string msgCLEANSEMATCH {
            get {
                return ResourceManager.GetString("msgCLEANSEMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string msgCompleted {
            get {
                return ResourceManager.GetString("msgCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executions.
        /// </summary>
        public static string msgExecutions {
            get {
                return ResourceManager.GetString("msgExecutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string msgFailed {
            get {
                return ResourceManager.GetString("msgFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Process.
        /// </summary>
        public static string msgLastProcess {
            get {
                return ResourceManager.GetString("msgLastProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        public static string msgMinute {
            get {
                return ResourceManager.GetString("msgMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No record(s) available.
        /// </summary>
        public static string msgNoRecords {
            get {
                return ResourceManager.GetString("msgNoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string msgRunning {
            get {
                return ResourceManager.GetString("msgRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful.
        /// </summary>
        public static string msgSuccessful {
            get {
                return ResourceManager.GetString("msgSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Data Queue Detail Report.
        /// </summary>
        public static string titleActiveDataQueueDetailReport {
            get {
                return ResourceManager.GetString("titleActiveDataQueueDetailReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matchbook | API Usage Statistics.
        /// </summary>
        public static string titleAPIStatistics {
            get {
                return ResourceManager.GetString("titleAPIStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Data Queue Statistics.
        /// </summary>
        public static string titleDownloadDataQueueStatistics {
            get {
                return ResourceManager.GetString("titleDownloadDataQueueStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matchbook | OI Dashboard.
        /// </summary>
        public static string titleOIDashboard {
            get {
                return ResourceManager.GetString("titleOIDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Active Data Queue Statistics.
        /// </summary>
        public static string titleRefreshActiveDataQueueStatistics {
            get {
                return ResourceManager.GetString("titleRefreshActiveDataQueueStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Background Process Statistics.
        /// </summary>
        public static string titleRefreshBackgroundProcessStatistics {
            get {
                return ResourceManager.GetString("titleRefreshBackgroundProcessStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Data Stewardship Statistics.
        /// </summary>
        public static string titleRefreshDataStewardshipStatistics {
            get {
                return ResourceManager.GetString("titleRefreshDataStewardshipStatistics", resourceCulture);
            }
        }
    }
}
