//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBISCCMWeb.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OIMatchDataLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OIMatchDataLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SBISCCMWeb.LanguageResources.OI.OIMatchDataLang", typeof(OIMatchDataLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept From File.
        /// </summary>
        public static string hdrAcceptFromFile {
            get {
                return ResourceManager.GetString("hdrAcceptFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new company.
        /// </summary>
        public static string hdrAddnewcompany {
            get {
                return ResourceManager.GetString("hdrAddnewcompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User Match Filter.
        /// </summary>
        public static string hdrAddUserMatchFilter {
            get {
                return ResourceManager.GetString("hdrAddUserMatchFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Information.
        /// </summary>
        public static string hdrCompanyInformation {
            get {
                return ResourceManager.GetString("hdrCompanyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User Match Filter.
        /// </summary>
        public static string hdrEditUserMatchFilter {
            get {
                return ResourceManager.GetString("hdrEditUserMatchFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Un-Match Data.
        /// </summary>
        public static string hdrExportUnMatchData {
            get {
                return ResourceManager.GetString("hdrExportUnMatchData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please map your file columns to the corresponding table columns.
        /// </summary>
        public static string hdrFileMapping {
            get {
                return ResourceManager.GetString("hdrFileMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Data.
        /// </summary>
        public static string hdrMatchData {
            get {
                return ResourceManager.GetString("hdrMatchData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Record Detail View.
        /// </summary>
        public static string hdrMatchRecordDetailView {
            get {
                return ResourceManager.GetString("hdrMatchRecordDetailView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Data.
        /// </summary>
        public static string hdrSearchData {
            get {
                return ResourceManager.GetString("hdrSearchData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit For Investigation.
        /// </summary>
        public static string hdrSubmitForInvestigation {
            get {
                return ResourceManager.GetString("hdrSubmitForInvestigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Candidates on Map.
        /// </summary>
        public static string hdrViewCandidatesonMap {
            get {
                return ResourceManager.GetString("hdrViewCandidatesonMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Accepts only Excel files).
        /// </summary>
        public static string lblAcceptExcel {
            get {
                return ResourceManager.GetString("lblAcceptExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepts only Excel files.
        /// </summary>
        public static string lblAcceptsonlyExcelfiles {
            get {
                return ResourceManager.GetString("lblAcceptsonlyExcelfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Only.
        /// </summary>
        public static string lblActiveOnly {
            get {
                return ResourceManager.GetString("lblActiveOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string lblAdd {
            get {
                return ResourceManager.GetString("lblAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Company.
        /// </summary>
        public static string lblAddCompany {
            get {
                return ResourceManager.GetString("lblAddCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Actions.
        /// </summary>
        public static string lblAdditionalActions {
            get {
                return ResourceManager.GetString("lblAdditionalActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string lblAddress {
            get {
                return ResourceManager.GetString("lblAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 1.
        /// </summary>
        public static string lblAddress1 {
            get {
                return ResourceManager.GetString("lblAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 2.
        /// </summary>
        public static string lblAddress2 {
            get {
                return ResourceManager.GetString("lblAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string lblAll {
            get {
                return ResourceManager.GetString("lblAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt.Address.
        /// </summary>
        public static string lblAltAddress {
            get {
                return ResourceManager.GetString("lblAltAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Orb.
        /// </summary>
        public static string lblAssignOrb {
            get {
                return ResourceManager.GetString("lblAssignOrb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bing Search.
        /// </summary>
        public static string lblBingSearch {
            get {
                return ResourceManager.GetString("lblBingSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidate.
        /// </summary>
        public static string lblCandidate {
            get {
                return ResourceManager.GetString("lblCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidate Count.
        /// </summary>
        public static string lblCandidateCount {
            get {
                return ResourceManager.GetString("lblCandidateCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC.
        /// </summary>
        public static string lblCC {
            get {
                return ResourceManager.GetString("lblCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC From.
        /// </summary>
        public static string lblCCFrom {
            get {
                return ResourceManager.GetString("lblCCFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCMax.
        /// </summary>
        public static string lblCCMax {
            get {
                return ResourceManager.GetString("lblCCMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCMin.
        /// </summary>
        public static string lblCCMin {
            get {
                return ResourceManager.GetString("lblCCMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC:Tot/Avg/Max/Min :.
        /// </summary>
        public static string lblCCTotAvgMaxMin {
            get {
                return ResourceManager.GetString("lblCCTotAvgMaxMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string lblCity {
            get {
                return ResourceManager.GetString("lblCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City/Town.
        /// </summary>
        public static string lblCityTown {
            get {
                return ResourceManager.GetString("lblCityTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string lblCompany {
            get {
                return ResourceManager.GetString("lblCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string lblCompanyName {
            get {
                return ResourceManager.GetString("lblCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Score.
        /// </summary>
        public static string lblCompanyScore {
            get {
                return ResourceManager.GetString("lblCompanyScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string lblCopy {
            get {
                return ResourceManager.GetString("lblCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string lblCountry {
            get {
                return ResourceManager.GetString("lblCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Group.
        /// </summary>
        public static string lblCountryGroup {
            get {
                return ResourceManager.GetString("lblCountryGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string lblDelete {
            get {
                return ResourceManager.GetString("lblDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Company Data.
        /// </summary>
        public static string lblDeleteCompanyData {
            get {
                return ResourceManager.GetString("lblDeleteCompanyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Data.
        /// </summary>
        public static string lblDeleteData {
            get {
                return ResourceManager.GetString("lblDeleteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Data From File.
        /// </summary>
        public static string lblDeleteDataFromFile {
            get {
                return ResourceManager.GetString("lblDeleteDataFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete From File.
        /// </summary>
        public static string lblDeleteFromFile {
            get {
                return ResourceManager.GetString("lblDeleteFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string lblEdit {
            get {
                return ResourceManager.GetString("lblEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EIN.
        /// </summary>
        public static string lblEIN {
            get {
                return ResourceManager.GetString("lblEIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable / Disabled.
        /// </summary>
        public static string lblEnableDisabled {
            get {
                return ResourceManager.GetString("lblEnableDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude.
        /// </summary>
        public static string lblExclude {
            get {
                return ResourceManager.GetString("lblExclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export To Excel.
        /// </summary>
        public static string lblExportToExcel {
            get {
                return ResourceManager.GetString("lblExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fine-tune Result Filters.
        /// </summary>
        public static string lblFinetuneResultFilters {
            get {
                return ResourceManager.GetString("lblFinetuneResultFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Search.
        /// </summary>
        public static string lblGoogleSearch {
            get {
                return ResourceManager.GetString("lblGoogleSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Process.
        /// </summary>
        public static string lblImportProcess {
            get {
                return ResourceManager.GetString("lblImportProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include data with candidates.
        /// </summary>
        public static string lblIncludedatawithCandidates {
            get {
                return ResourceManager.GetString("lblIncludedatawithCandidates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include data with zero candidates.
        /// </summary>
        public static string lblIncludewithzeroCandidates {
            get {
                return ResourceManager.GetString("lblIncludewithzeroCandidates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string lblInput {
            get {
                return ResourceManager.GetString("lblInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Header.
        /// </summary>
        public static string lblInputHeader {
            get {
                return ResourceManager.GetString("lblInputHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinkedIn Search.
        /// </summary>
        public static string lblLinkedInSearch {
            get {
                return ResourceManager.GetString("lblLinkedInSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Data.
        /// </summary>
        public static string lblMatchData {
            get {
                return ResourceManager.GetString("lblMatchData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches.
        /// </summary>
        public static string lblMatches {
            get {
                return ResourceManager.GetString("lblMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Grade.
        /// </summary>
        public static string lblMatchGrade {
            get {
                return ResourceManager.GetString("lblMatchGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MDP.
        /// </summary>
        public static string lblMDP {
            get {
                return ResourceManager.GetString("lblMDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MDP Code.
        /// </summary>
        public static string lblMDPCode {
            get {
                return ResourceManager.GetString("lblMDPCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MDP Value.
        /// </summary>
        public static string lblMDPValue {
            get {
                return ResourceManager.GetString("lblMDPValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string lblMessage {
            get {
                return ResourceManager.GetString("lblMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.Match Score.
        /// </summary>
        public static string lblMinMatchScore {
            get {
                return ResourceManager.GetString("lblMinMatchScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string lblNext {
            get {
                return ResourceManager.GetString("lblNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Candidate.
        /// </summary>
        public static string lblNoCandidate {
            get {
                return ResourceManager.GetString("lblNoCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data are available.
        /// </summary>
        public static string lblNodataareavailable {
            get {
                return ResourceManager.GetString("lblNodataareavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No filter records available.
        /// </summary>
        public static string lblNofilterrecordsavailable {
            get {
                return ResourceManager.GetString("lblNofilterrecordsavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records found..
        /// </summary>
        public static string lblNorecordsfound {
            get {
                return ResourceManager.GetString("lblNorecordsfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Filters: No Filters Set.
        /// </summary>
        public static string lblNoSessionFilters {
            get {
                return ResourceManager.GetString("lblNoSessionFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating.
        /// </summary>
        public static string lblOperating {
            get {
                return ResourceManager.GetString("lblOperating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORB#.
        /// </summary>
        public static string lblORB {
            get {
                return ResourceManager.GetString("lblORB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orb Data.
        /// </summary>
        public static string lblOrbData {
            get {
                return ResourceManager.GetString("lblOrbData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORB NO.
        /// </summary>
        public static string lblORBNO {
            get {
                return ResourceManager.GetString("lblORBNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orb Num.
        /// </summary>
        public static string lblOrbNum {
            get {
                return ResourceManager.GetString("lblOrbNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orb Number.
        /// </summary>
        public static string lblOrbNumber {
            get {
                return ResourceManager.GetString("lblOrbNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Size.
        /// </summary>
        public static string lblPageSize {
            get {
                return ResourceManager.GetString("lblPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string lblPhone {
            get {
                return ResourceManager.GetString("lblPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhoneNbr.
        /// </summary>
        public static string lblPhoneNbr {
            get {
                return ResourceManager.GetString("lblPhoneNbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string lblPhoneNumber {
            get {
                return ResourceManager.GetString("lblPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill SrcRecordId.
        /// </summary>
        public static string lblPleasefillSrcRecordId {
            get {
                return ResourceManager.GetString("lblPleasefillSrcRecordId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string lblPostalCode {
            get {
                return ResourceManager.GetString("lblPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        public static string lblPrev {
            get {
                return ResourceManager.GetString("lblPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        public static string lblRank {
            get {
                return ResourceManager.GetString("lblRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank#.
        /// </summary>
        public static string lblRanking {
            get {
                return ResourceManager.GetString("lblRanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string lblRefresh {
            get {
                return ResourceManager.GetString("lblRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Stewardship Queue.
        /// </summary>
        public static string lblRefreshStewardshipQueue {
            get {
                return ResourceManager.GetString("lblRefreshStewardshipQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string lblReject {
            get {
                return ResourceManager.GetString("lblReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject Candidate.
        /// </summary>
        public static string lblRejectCandidate {
            get {
                return ResourceManager.GetString("lblRejectCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill Company.
        /// </summary>
        public static string lblRequiredCompany {
            get {
                return ResourceManager.GetString("lblRequiredCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SrcRecordId is required.
        /// </summary>
        public static string lblRequiredSrcRecordId {
            get {
                return ResourceManager.GetString("lblRequiredSrcRecordId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag is required..
        /// </summary>
        public static string lblRequiredTag {
            get {
                return ResourceManager.GetString("lblRequiredTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string lblSearch {
            get {
                return ResourceManager.GetString("lblSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by address.
        /// </summary>
        public static string lblSearchbyaddress {
            get {
                return ResourceManager.GetString("lblSearchbyaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by company.
        /// </summary>
        public static string lblSearchbycompany {
            get {
                return ResourceManager.GetString("lblSearchbycompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by EIN.
        /// </summary>
        public static string lblSearchbyEIN {
            get {
                return ResourceManager.GetString("lblSearchbyEIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by email.
        /// </summary>
        public static string lblSearchbyemail {
            get {
                return ResourceManager.GetString("lblSearchbyemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by orb number.
        /// </summary>
        public static string lblSearchbyorbnumber {
            get {
                return ResourceManager.GetString("lblSearchbyorbnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by web domain.
        /// </summary>
        public static string lblSearchbywebdomain {
            get {
                return ResourceManager.GetString("lblSearchbywebdomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string lblSelect {
            get {
                return ResourceManager.GetString("lblSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string lblSelectAll {
            get {
                return ResourceManager.GetString("lblSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to ORB.
        /// </summary>
        public static string lblSendtoORB {
            get {
                return ResourceManager.GetString("lblSendtoORB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Filters.
        /// </summary>
        public static string lblSessionFilters {
            get {
                return ResourceManager.GetString("lblSessionFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Src Id.
        /// </summary>
        public static string lblSrcId {
            get {
                return ResourceManager.GetString("lblSrcId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SrcRecordId.
        /// </summary>
        public static string lblSrcRecordId {
            get {
                return ResourceManager.GetString("lblSrcRecordId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string lblState {
            get {
                return ResourceManager.GetString("lblState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street#.
        /// </summary>
        public static string lblStreet {
            get {
                return ResourceManager.GetString("lblStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Name.
        /// </summary>
        public static string lblStreetName {
            get {
                return ResourceManager.GetString("lblStreetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Column.
        /// </summary>
        public static string lblTableColumn {
            get {
                return ResourceManager.GetString("lblTableColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string lblTag {
            get {
                return ResourceManager.GetString("lblTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string lblTags {
            get {
                return ResourceManager.GetString("lblTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string lblTo {
            get {
                return ResourceManager.GetString("lblTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tot/Avg/Max/Min.
        /// </summary>
        public static string lblTotAvgMaxMin {
            get {
                return ResourceManager.GetString("lblTotAvgMaxMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string lblType {
            get {
                return ResourceManager.GetString("lblType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo Delete.
        /// </summary>
        public static string lblUndoDelete {
            get {
                return ResourceManager.GetString("lblUndoDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string lblUpdate {
            get {
                return ResourceManager.GetString("lblUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Candidates on Map.
        /// </summary>
        public static string lblViewCandidatesonMap {
            get {
                return ResourceManager.GetString("lblViewCandidatesonMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Domain.
        /// </summary>
        public static string lblWebDomain {
            get {
                return ResourceManager.GetString("lblWebDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webdomain.
        /// </summary>
        public static string lblWebdomains {
            get {
                return ResourceManager.GetString("lblWebdomains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string lblWebsite {
            get {
                return ResourceManager.GetString("lblWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Candidates.
        /// </summary>
        public static string lblWithCandidates {
            get {
                return ResourceManager.GetString("lblWithCandidates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without Candidates.
        /// </summary>
        public static string lblWithoutCandidates {
            get {
                return ResourceManager.GetString("lblWithoutCandidates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add match as a new company.
        /// </summary>
        public static string msgAddMatchAsCompany {
            get {
                return ResourceManager.GetString("msgAddMatchAsCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New company added successfully.
        /// </summary>
        public static string msgAddNewCompany {
            get {
                return ResourceManager.GetString("msgAddNewCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to Assign ORB number?.
        /// </summary>
        public static string msgAssignORB {
            get {
                return ResourceManager.GetString("msgAssignORB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Deleted Successfully.
        /// </summary>
        public static string msgDataDeleted {
            get {
                return ResourceManager.GetString("msgDataDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data updated successfully.
        /// </summary>
        public static string msgDataUpdated {
            get {
                return ResourceManager.GetString("msgDataUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to Delete company data ?.
        /// </summary>
        public static string msgDeleteCompanyData {
            get {
                return ResourceManager.GetString("msgDeleteCompanyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete record ?.
        /// </summary>
        public static string msgDeleteRecord {
            get {
                return ResourceManager.GetString("msgDeleteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this Search ?.
        /// </summary>
        public static string msgDeleteSearch {
            get {
                return ResourceManager.GetString("msgDeleteSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record disable successfully.
        /// </summary>
        public static string msgdisableRecord {
            get {
                return ResourceManager.GetString("msgdisableRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to disable record ?.
        /// </summary>
        public static string msgDisableRecordConfirmBox {
            get {
                return ResourceManager.GetString("msgDisableRecordConfirmBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record enable successfully.
        /// </summary>
        public static string msgEnableRecord {
            get {
                return ResourceManager.GetString("msgEnableRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to enable record ?.
        /// </summary>
        public static string msgEnableRecordConfirmBox {
            get {
                return ResourceManager.GetString("msgEnableRecordConfirmBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Excel.
        /// </summary>
        public static string msgExporttoExcel {
            get {
                return ResourceManager.GetString("msgExporttoExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only formats allowed are :.
        /// </summary>
        public static string msgMatchAcceptAllowedFormats {
            get {
                return ResourceManager.GetString("msgMatchAcceptAllowedFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum 10 searches are allowed..
        /// </summary>
        public static string msgMaximumSearchAllowed {
            get {
                return ResourceManager.GetString("msgMaximumSearchAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maximum value must be greater than minimum value..
        /// </summary>
        public static string msgMaxValue {
            get {
                return ResourceManager.GetString("msgMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No record(s) found.
        /// </summary>
        public static string msgNoRecords {
            get {
                return ResourceManager.GetString("msgNoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reject this candidate?.
        /// </summary>
        public static string msgRejectCandidate {
            get {
                return ResourceManager.GetString("msgRejectCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to restore last delete ?.
        /// </summary>
        public static string msgRestoreDelete {
            get {
                return ResourceManager.GetString("msgRestoreDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select at least one search.
        /// </summary>
        public static string msgSelectSearch {
            get {
                return ResourceManager.GetString("msgSelectSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload only.
        /// </summary>
        public static string msgUploadCertainFile {
            get {
                return ResourceManager.GetString("msgUploadCertainFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address1.
        /// </summary>
        public static string placeholderAddress1 {
            get {
                return ResourceManager.GetString("placeholderAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address2.
        /// </summary>
        public static string placeholderAddress2 {
            get {
                return ResourceManager.GetString("placeholderAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string placeholderCity {
            get {
                return ResourceManager.GetString("placeholderCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanyName.
        /// </summary>
        public static string placeholderCompanyName {
            get {
                return ResourceManager.GetString("placeholderCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EIN.
        /// </summary>
        public static string placeholderEIN {
            get {
                return ResourceManager.GetString("placeholderEIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string placeholderEmail {
            get {
                return ResourceManager.GetString("placeholderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orb Number.
        /// </summary>
        public static string placeholderOrbNumber {
            get {
                return ResourceManager.GetString("placeholderOrbNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string placeholderPhone {
            get {
                return ResourceManager.GetString("placeholderPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search the web.
        /// </summary>
        public static string placeholderSearchWeb {
            get {
                return ResourceManager.GetString("placeholderSearchWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string placeholderWebsite {
            get {
                return ResourceManager.GetString("placeholderWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip.
        /// </summary>
        public static string placeholderZip {
            get {
                return ResourceManager.GetString("placeholderZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string placeholoderState {
            get {
                return ResourceManager.GetString("placeholoderState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse.
        /// </summary>
        public static string titleCollapse {
            get {
                return ResourceManager.GetString("titleCollapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string titleDelete {
            get {
                return ResourceManager.GetString("titleDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De-Select.
        /// </summary>
        public static string titleDeSelect {
            get {
                return ResourceManager.GetString("titleDeSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string titleEdit {
            get {
                return ResourceManager.GetString("titleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand.
        /// </summary>
        public static string titleExpand {
            get {
                return ResourceManager.GetString("titleExpand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matchbook | OI Match Data.
        /// </summary>
        public static string titleOIMatchData {
            get {
                return ResourceManager.GetString("titleOIMatchData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string titleSubmit {
            get {
                return ResourceManager.GetString("titleSubmit", resourceCulture);
            }
        }
    }
}
