//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBISCCMWeb.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OISettingLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OISettingLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SBISCCMWeb.LanguageResources.OI.OISettingLang", typeof(OISettingLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Auto Acceptance Rules.
        /// </summary>
        public static string hdrAddAutoAcceptanceRules {
            get {
                return ResourceManager.GetString("hdrAddAutoAcceptanceRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Acceptance.
        /// </summary>
        public static string hdrAutoAcceptance {
            get {
                return ResourceManager.GetString("hdrAutoAcceptance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-Accept Directives.
        /// </summary>
        public static string hdrAutoAcceptDirectives {
            get {
                return ResourceManager.GetString("hdrAutoAcceptDirectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Process Settings.
        /// </summary>
        public static string hdrBackgroundProcessSettings {
            get {
                return ResourceManager.GetString("hdrBackgroundProcessSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Auto Acceptance Rules.
        /// </summary>
        public static string hdrEditAutoAcceptanceRules {
            get {
                return ResourceManager.GetString("hdrEditAutoAcceptanceRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Data Handling.
        /// </summary>
        public static string hdrImportDataHandling {
            get {
                return ResourceManager.GetString("hdrImportDataHandling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orb Credentials.
        /// </summary>
        public static string hdrOrbCredentials {
            get {
                return ResourceManager.GetString("hdrOrbCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Data.
        /// </summary>
        public static string hdrResetData {
            get {
                return ResourceManager.GetString("hdrResetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key.
        /// </summary>
        public static string lbAPIKey {
            get {
                return ResourceManager.GetString("lbAPIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Active Records Only.
        /// </summary>
        public static string lblAcceptActiveRecordsOnly {
            get {
                return ResourceManager.GetString("lblAcceptActiveRecordsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string lblAdd {
            get {
                return ResourceManager.GetString("lblAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API key is required..
        /// </summary>
        public static string lblAPIkeyisrequired {
            get {
                return ResourceManager.GetString("lblAPIkeyisrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC From.
        /// </summary>
        public static string lblCCFrom {
            get {
                return ResourceManager.GetString("lblCCFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCMax.
        /// </summary>
        public static string lblCCMax {
            get {
                return ResourceManager.GetString("lblCCMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCMin.
        /// </summary>
        public static string lblCCMin {
            get {
                return ResourceManager.GetString("lblCCMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string lblCity {
            get {
                return ResourceManager.GetString("lblCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string lblCompany {
            get {
                return ResourceManager.GetString("lblCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Score.
        /// </summary>
        public static string lblCompanyScore {
            get {
                return ResourceManager.GetString("lblCompanyScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string lblCountry {
            get {
                return ResourceManager.GetString("lblCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Group.
        /// </summary>
        public static string lblCountryGroup {
            get {
                return ResourceManager.GetString("lblCountryGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string lblDelete {
            get {
                return ResourceManager.GetString("lblDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t import data already in Matchbook Queues.
        /// </summary>
        public static string lblDontimportdataalreadyinMatchbookQueues {
            get {
                return ResourceManager.GetString("lblDontimportdataalreadyinMatchbookQueues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string lblEdit {
            get {
                return ResourceManager.GetString("lblEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EIN.
        /// </summary>
        public static string lblEIN {
            get {
                return ResourceManager.GetString("lblEIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Batch Size.
        /// </summary>
        public static string lblEnterBatchSize {
            get {
                return ResourceManager.GetString("lblEnterBatchSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter BATCH WAITTIME SECS.
        /// </summary>
        public static string lblEnterBATCHWAITTIMESECS {
            get {
                return ResourceManager.GetString("lblEnterBATCHWAITTIMESECS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Max Parallel Threads.
        /// </summary>
        public static string lblEnterMaxParallelThreads {
            get {
                return ResourceManager.GetString("lblEnterMaxParallelThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude From Auto Accept.
        /// </summary>
        public static string lblExcludeFromAutoAccept {
            get {
                return ResourceManager.GetString("lblExcludeFromAutoAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity Resolution.
        /// </summary>
        public static string lblIdentityResolution {
            get {
                return ResourceManager.GetString("lblIdentityResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string lblLicense {
            get {
                return ResourceManager.GetString("lblLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Grade.
        /// </summary>
        public static string lblMatchGrade {
            get {
                return ResourceManager.GetString("lblMatchGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MDP Code.
        /// </summary>
        public static string lblMDPCode {
            get {
                return ResourceManager.GetString("lblMDPCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MDP Value.
        /// </summary>
        public static string lblMDPValue {
            get {
                return ResourceManager.GetString("lblMDPValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.Match Score.
        /// </summary>
        public static string lblMinMatchScore {
            get {
                return ResourceManager.GetString("lblMinMatchScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data are available.
        /// </summary>
        public static string lblNodataareavailable {
            get {
                return ResourceManager.GetString("lblNodataareavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No duplicate check for import.
        /// </summary>
        public static string lblNoduplicatecheckforimport {
            get {
                return ResourceManager.GetString("lblNoduplicatecheckforimport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORB BATCH SIZE.
        /// </summary>
        public static string lblORBBATCHSIZE {
            get {
                return ResourceManager.GetString("lblORBBATCHSIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORB BATCH WAITTIME SECS.
        /// </summary>
        public static string lblORBBATCHWAITTIMESECS {
            get {
                return ResourceManager.GetString("lblORBBATCHWAITTIMESECS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORB DATA IMPORT DUPLICATE RESOLUTION TAGS.
        /// </summary>
        public static string lblORBDATAIMPORTDUPLICATERESOLUTIONTAGS {
            get {
                return ResourceManager.GetString("lblORBDATAIMPORTDUPLICATERESOLUTIONTAGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORB ENABLE CORPORATE TREE ENRICHMENT.
        /// </summary>
        public static string lblORBENABLECORPORATETREEENRICHMENT {
            get {
                return ResourceManager.GetString("lblORBENABLECORPORATETREEENRICHMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORB MAX PARALLEL THREADS.
        /// </summary>
        public static string lblORBMAXPARALLELTHREADS {
            get {
                return ResourceManager.GetString("lblORBMAXPARALLELTHREADS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAUSE ORB BATCHMATCH ETL.
        /// </summary>
        public static string lblPAUSEORBBATCHMATCHETL {
            get {
                return ResourceManager.GetString("lblPAUSEORBBATCHMATCHETL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string lblPhone {
            get {
                return ResourceManager.GetString("lblPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type &apos;YES&apos; to reset data..
        /// </summary>
        public static string lblPleasetypeYEStoresetdata {
            get {
                return ResourceManager.GetString("lblPleasetypeYEStoresetdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string lblPostalCode {
            get {
                return ResourceManager.GetString("lblPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer Linked Records.
        /// </summary>
        public static string lblPreferLinkedRecords {
            get {
                return ResourceManager.GetString("lblPreferLinkedRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove duplicate records from Active and Output Queues.
        /// </summary>
        public static string lblRemoveduplicaterecordsfromActiveandOutputQueues {
            get {
                return ResourceManager.GetString("lblRemoveduplicaterecordsfromActiveandOutputQueues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove duplicate records from the Active Queues.
        /// </summary>
        public static string lblRemoveduplicaterecordsfromtheActiveQueues {
            get {
                return ResourceManager.GetString("lblRemoveduplicaterecordsfromtheActiveQueues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string lblReset {
            get {
                return ResourceManager.GetString("lblReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset OI Data.
        /// </summary>
        public static string lblResetOIData {
            get {
                return ResourceManager.GetString("lblResetOIData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string lblState {
            get {
                return ResourceManager.GetString("lblState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street#.
        /// </summary>
        public static string lblStreet {
            get {
                return ResourceManager.GetString("lblStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Name.
        /// </summary>
        public static string lblStreetName {
            get {
                return ResourceManager.GetString("lblStreetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street No.
        /// </summary>
        public static string lblStreetNo {
            get {
                return ResourceManager.GetString("lblStreetNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag is required..
        /// </summary>
        public static string lblTagisrequired {
            get {
                return ResourceManager.GetString("lblTagisrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string lblTags {
            get {
                return ResourceManager.GetString("lblTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string lblTo {
            get {
                return ResourceManager.GetString("lblTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string lblUpdate {
            get {
                return ResourceManager.GetString("lblUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter only numeric.
        /// </summary>
        public static string lblValidBatch {
            get {
                return ResourceManager.GetString("lblValidBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Domain.
        /// </summary>
        public static string lblWebDomain {
            get {
                return ResourceManager.GetString("lblWebDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maximum value must be greater than minimum value..
        /// </summary>
        public static string msgConfidenceCodeMinMaxValue {
            get {
                return ResourceManager.GetString("msgConfidenceCodeMinMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data deleted successfully.
        /// </summary>
        public static string msgDataDeleted {
            get {
                return ResourceManager.GetString("msgDataDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete record ?.
        /// </summary>
        public static string msgDeleteAutoAcceptanceRecord {
            get {
                return ResourceManager.GetString("msgDeleteAutoAcceptanceRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete record?.
        /// </summary>
        public static string msgDeleteThirdPartyAPICredentials {
            get {
                return ResourceManager.GetString("msgDeleteThirdPartyAPICredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to Reset Data ?.
        /// </summary>
        public static string msgResetOIData {
            get {
                return ResourceManager.GetString("msgResetOIData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select City Grade.
        /// </summary>
        public static string msgSelectCityGrade {
            get {
                return ResourceManager.GetString("msgSelectCityGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Company Code.
        /// </summary>
        public static string msgSelectCompanyCode {
            get {
                return ResourceManager.GetString("msgSelectCompanyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Company Grade.
        /// </summary>
        public static string msgSelectCompanyGrade {
            get {
                return ResourceManager.GetString("msgSelectCompanyGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Country Grade.
        /// </summary>
        public static string msgSelectCountryGrade {
            get {
                return ResourceManager.GetString("msgSelectCountryGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select EIN Grade.
        /// </summary>
        public static string msgSelectEINGrade {
            get {
                return ResourceManager.GetString("msgSelectEINGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Phone Grade.
        /// </summary>
        public static string msgSelectPhoneGrade {
            get {
                return ResourceManager.GetString("msgSelectPhoneGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Postal Code Grade.
        /// </summary>
        public static string msgSelectPostalCodeGrade {
            get {
                return ResourceManager.GetString("msgSelectPostalCodeGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select State Grade.
        /// </summary>
        public static string msgSelectStateGrade {
            get {
                return ResourceManager.GetString("msgSelectStateGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Street Grade.
        /// </summary>
        public static string msgSelectStreetGrade {
            get {
                return ResourceManager.GetString("msgSelectStreetGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Street Name Grade.
        /// </summary>
        public static string msgSelectStreetNameGrade {
            get {
                return ResourceManager.GetString("msgSelectStreetNameGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Web Domain Code.
        /// </summary>
        public static string msgSelectWebDomainCode {
            get {
                return ResourceManager.GetString("msgSelectWebDomainCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Web Domain Grade.
        /// </summary>
        public static string msgSelectWebDomainGrade {
            get {
                return ResourceManager.GetString("msgSelectWebDomainGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matchbook | Orb Intelligence.
        /// </summary>
        public static string titleOrbIntelligence {
            get {
                return ResourceManager.GetString("titleOrbIntelligence", resourceCulture);
            }
        }
    }
}
