//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBISCCMWeb.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OrbMenuLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrbMenuLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SBISCCMWeb.LanguageResources.OI.OrbMenuLang", typeof(OrbMenuLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Users.
        /// </summary>
        public static string lblActiveUsers {
            get {
                return ResourceManager.GetString("lblActiveUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackGround Process Status.
        /// </summary>
        public static string lblBackGroundProcessStatus {
            get {
                return ResourceManager.GetString("lblBackGroundProcessStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build A List.
        /// </summary>
        public static string lblBuildAList {
            get {
                return ResourceManager.GetString("lblBuildAList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string lblDashboard {
            get {
                return ResourceManager.GetString("lblDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Data.
        /// </summary>
        public static string lblExportData {
            get {
                return ResourceManager.GetString("lblExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Desk.
        /// </summary>
        public static string lblHelpDesk {
            get {
                return ResourceManager.GetString("lblHelpDesk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Data.
        /// </summary>
        public static string lblImportData {
            get {
                return ResourceManager.GetString("lblImportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investigation Report.
        /// </summary>
        public static string lblInvestigationReport {
            get {
                return ResourceManager.GetString("lblInvestigationReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Data.
        /// </summary>
        public static string lblMatchData {
            get {
                return ResourceManager.GetString("lblMatchData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orb Intelligence.
        /// </summary>
        public static string lblOrbIntelligence {
            get {
                return ResourceManager.GetString("lblOrbIntelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal.
        /// </summary>
        public static string lblPortal {
            get {
                return ResourceManager.GetString("lblPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prospecting.
        /// </summary>
        public static string lblProspecting {
            get {
                return ResourceManager.GetString("lblProspecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string lblReports {
            get {
                return ResourceManager.GetString("lblReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Data.
        /// </summary>
        public static string lblSearchData {
            get {
                return ResourceManager.GetString("lblSearchData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string lblSettings {
            get {
                return ResourceManager.GetString("lblSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build A List.
        /// </summary>
        public static string titleBuildAList {
            get {
                return ResourceManager.GetString("titleBuildAList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string titleDashboard {
            get {
                return ResourceManager.GetString("titleDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Data.
        /// </summary>
        public static string titleExportData {
            get {
                return ResourceManager.GetString("titleExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Desk.
        /// </summary>
        public static string titleHelpDesk {
            get {
                return ResourceManager.GetString("titleHelpDesk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Data.
        /// </summary>
        public static string titleImportData {
            get {
                return ResourceManager.GetString("titleImportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investigation Report.
        /// </summary>
        public static string titleInvestigationReport {
            get {
                return ResourceManager.GetString("titleInvestigationReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Data.
        /// </summary>
        public static string titleMatchData {
            get {
                return ResourceManager.GetString("titleMatchData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orb Intelligence.
        /// </summary>
        public static string titleOrbIntelligence {
            get {
                return ResourceManager.GetString("titleOrbIntelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orb Intelligence Data.
        /// </summary>
        public static string titleOrbIntelligenceData {
            get {
                return ResourceManager.GetString("titleOrbIntelligenceData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal.
        /// </summary>
        public static string titlePortal {
            get {
                return ResourceManager.GetString("titlePortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prospecting.
        /// </summary>
        public static string titleProspecting {
            get {
                return ResourceManager.GetString("titleProspecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string titleReports {
            get {
                return ResourceManager.GetString("titleReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Data.
        /// </summary>
        public static string titleSearchData {
            get {
                return ResourceManager.GetString("titleSearchData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string titleSettings {
            get {
                return ResourceManager.GetString("titleSettings", resourceCulture);
            }
        }
    }
}
